const phraseModules = {

"real-life":[

{id:1,en:"Can you help me, please?",ar:"ممكن تساعدني لو سمحت؟",note:"طلب مساعدة"},
{id:2,en:"I need some help.",ar:"أنا محتاج مساعدة.",note:"طلب مساعدة"},
{id:3,en:"Please wait a moment.",ar:"استنى لحظة لو سمحت.",note:"طلب وقت"},
{id:4,en:"I have a problem.",ar:"عندي مشكلة.",note:"شرح موقف"},
{id:5,en:"What should I do?",ar:"أعمل إيه؟",note:"طلب نصيحة"},
{id:6,en:"I don't understand.",ar:"أنا مش فاهم.",note:"عدم فهم"},
{id:7,en:"Can you repeat that?",ar:"ممكن تعيد؟",note:"طلب إعادة"},
{id:8,en:"Speak slowly, please.",ar:"اتكلم ببطء لو سمحت.",note:"مساعدة في الفهم"},
{id:9,en:"I am lost.",ar:"أنا تايه.",note:"اتجاهات"},
{id:10,en:"Where am I?",ar:"أنا فين؟",note:"اتجاهات"},

{id:11,en:"Can you show me the way?",ar:"ممكن تدلني على الطريق؟",note:"طلب اتجاهات"},
{id:12,en:"I forgot my phone.",ar:"نسيت موبايلي.",note:"موقف يومي"},
{id:13,en:"My battery is dead.",ar:"البطارية فصلت.",note:"تكنولوجيا"},
{id:14,en:"I need a charger.",ar:"محتاج شاحن.",note:"طلب شيء"},
{id:15,en:"Do you have Wi-Fi?",ar:"عندكم واي فاي؟",note:"إنترنت"},
{id:16,en:"What's the password?",ar:"إيه الباسورد؟",note:"إنترنت"},
{id:17,en:"I can't open it.",ar:"مش عارف أفتحه.",note:"مشكلة"},
{id:18,en:"It's not working.",ar:"مش شغال.",note:"عطل"},
{id:19,en:"Try again.",ar:"حاول تاني.",note:"تشجيع"},
{id:20,en:"Don't worry.",ar:"متقلقش.",note:"طمأنة"},

{id:21,en:"Everything is okay.",ar:"كل حاجة تمام.",note:"طمأنة"},
{id:22,en:"Take your time.",ar:"خد وقتك.",note:"هدوء"},
{id:23,en:"I'm in a hurry.",ar:"أنا مستعجل.",note:"وقت"},
{id:24,en:"Let's go now.",ar:"يلا بينا دلوقتي.",note:"حركة"},
{id:25,en:"Wait here.",ar:"استنى هنا.",note:"تعليمات"},
{id:26,en:"Follow me.",ar:"امشي ورايا.",note:"اتجاهات"},
{id:27,en:"Be careful.",ar:"خلي بالك.",note:"تحذير"},
{id:28,en:"Watch your step.",ar:"خلي بالك وإنت ماشي.",note:"تحذير"},
{id:29,en:"I feel sick.",ar:"حاسس إني تعبان.",note:"صحة"},
{id:30,en:"I need a doctor.",ar:"محتاج دكتور.",note:"طوارئ"},

{id:31,en:"Call the police.",ar:"اتصل بالشرطة.",note:"طوارئ"},
{id:32,en:"Call an ambulance.",ar:"هات إسعاف.",note:"طوارئ"},
{id:33,en:"I lost my wallet.",ar:"محفظتي ضاعت.",note:"مشكلة"},
{id:34,en:"Someone stole my bag.",ar:"حد سرق شنطتي.",note:"سرقة"},
{id:35,en:"Can I use your phone?",ar:"ممكن أستخدم تليفونك؟",note:"طلب"},
{id:36,en:"I need some cash.",ar:"محتاج كاش.",note:"فلوس"},
{id:37,en:"Where is the ATM?",ar:"فين الـ ATM؟",note:"بنك"},
{id:38,en:"I don't have enough money.",ar:"معيش فلوس كفاية.",note:"فلوس"},
{id:39,en:"Can I pay by card?",ar:"ينفع أدفع كارت؟",note:"دفع"},
{id:40,en:"The price is too high.",ar:"السعر غالي جدًا.",note:"شراء"},

{id:41,en:"Can you lower the price?",ar:"ممكن تقلل السعر؟",note:"تفاوض"},
{id:42,en:"That's expensive.",ar:"ده غالي.",note:"شراء"},
{id:43,en:"That's cheap.",ar:"ده رخيص.",note:"شراء"},
{id:44,en:"I like this one.",ar:"عجبني ده.",note:"اختيار"},
{id:45,en:"Do you have another color?",ar:"عندك لون تاني؟",note:"تسوق"},
{id:46,en:"What size is this?",ar:"المقاس ده كام؟",note:"ملابس"},
{id:47,en:"It's too small.",ar:"ده صغير أوي.",note:"مقاسات"},
{id:48,en:"It's too big.",ar:"ده كبير أوي.",note:"مقاسات"},
{id:49,en:"Can I try it?",ar:"ممكن أقيسه؟",note:"تجربة"},
{id:50,en:"I will take it.",ar:"هاخده.",note:"شراء"},

{id:51,en:"I'm tired.",ar:"أنا تعبان.",note:"مشاعر"},
{id:52,en:"I need some rest.",ar:"محتاج أرتاح شوية.",note:"راحة"},
{id:53,en:"I feel better now.",ar:"حاسس إني أحسن دلوقتي.",note:"تحسن"},
{id:54,en:"I'm hungry.",ar:"أنا جعان.",note:"طعام"},
{id:55,en:"I'm thirsty.",ar:"أنا عطشان.",note:"طعام"},
{id:56,en:"Let's eat something.",ar:"يلا ناكل حاجة.",note:"طعام"},
{id:57,en:"I'm bored.",ar:"أنا زهقان.",note:"مشاعر"},
{id:58,en:"I'm happy today.",ar:"أنا مبسوط النهارده.",note:"مشاعر"},
{id:59,en:"I feel stressed.",ar:"حاسس بضغط.",note:"مشاعر"},
{id:60,en:"Calm down.",ar:"اهدى.",note:"تهدئة"},

{id:61,en:"I miss you.",ar:"إنت واحشني.",note:"علاقات"},
{id:62,en:"I trust you.",ar:"أنا بثق فيك.",note:"علاقات"},
{id:63,en:"Tell me the truth.",ar:"قولّي الحقيقة.",note:"حديث"},
{id:64,en:"I don't believe you.",ar:"أنا مش مصدقك.",note:"شك"},
{id:65,en:"I'm serious.",ar:"أنا بتكلم بجد.",note:"تأكيد"},
{id:66,en:"Are you kidding?",ar:"إنت بتهزر؟",note:"تعجب"},
{id:67,en:"That was funny.",ar:"دي كانت مضحكة.",note:"ضحك"},
{id:68,en:"What happened?",ar:"إيه اللي حصل؟",note:"سؤال"},
{id:69,en:"Nothing happened.",ar:"محصلش حاجة.",note:"رد"},
{id:70,en:"It's my fault.",ar:"ده غلطي.",note:"اعتراف"},

{id:71,en:"I'm sorry.",ar:"أنا آسف.",note:"اعتذار"},
{id:72,en:"No problem.",ar:"مفيش مشكلة.",note:"رد"},
{id:73,en:"Thank you so much.",ar:"شكراً جدًا.",note:"شكر"},
{id:74,en:"You're welcome.",ar:"العفو.",note:"رد"},
{id:75,en:"Excuse me.",ar:"لو سمحت.",note:"استئذان"},
{id:76,en:"Can I ask you something?",ar:"ممكن أسألك حاجة؟",note:"سؤال"},
{id:77,en:"Of course.",ar:"طبعًا.",note:"موافقة"},
{id:78,en:"I agree with you.",ar:"أنا متفق معاك.",note:"اتفاق"},
{id:79,en:"I don't agree.",ar:"أنا مش متفق.",note:"اختلاف"},
{id:80,en:"Maybe you're right.",ar:"يمكن معاك حق.",note:"رأي"},

{id:81,en:"Let's talk later.",ar:"نتكلم بعدين.",note:"تأجيل"},
{id:82,en:"I'm busy right now.",ar:"أنا مشغول دلوقتي.",note:"انشغال"},
{id:83,en:"Call me later.",ar:"كلمني بعدين.",note:"اتصال"},
{id:84,en:"Send me the address.",ar:"ابعتلي العنوان.",note:"معلومات"},
{id:85,en:"I'm outside.",ar:"أنا بره.",note:"مكان"},
{id:86,en:"I'm coming.",ar:"أنا جاي.",note:"حركة"},
{id:87,en:"I'm almost there.",ar:"أنا قربت أوصل.",note:"حركة"},
{id:88,en:"I just arrived.",ar:"لسه واصل حالًا.",note:"وصول"},
{id:89,en:"See you tomorrow.",ar:"أشوفك بكرة.",note:"وداع"},
{id:90,en:"Take care of yourself.",ar:"خلي بالك من نفسك.",note:"اهتمام"},

{id:91,en:"Good luck.",ar:"بالتوفيق.",note:"تشجيع"},
{id:92,en:"Congratulations!",ar:"مبروك!",note:"تهنئة"},
{id:93,en:"Happy birthday!",ar:"عيد ميلاد سعيد!",note:"مناسبة"},
{id:94,en:"Enjoy your day.",ar:"استمتع بيومك.",note:"إيجابية"},
{id:95,en:"Have a safe trip.",ar:"رحلة سعيدة.",note:"سفر"},
{id:96,en:"Drive safely.",ar:"اسوق بالراحة.",note:"تحذير"},
{id:97,en:"See you soon.",ar:"أشوفك قريب.",note:"وداع"},
{id:98,en:"Text me when you arrive.",ar:"ابعتلي لما توصل.",note:"متابعة"},
{id:99,en:"I appreciate your help.",ar:"مقدر مساعدتك.",note:"شكر"},
{id:100,en:"Everything will be fine.",ar:"كل حاجة هتبقى تمام.",note:"طمأنة"},
{id:101,en:"I'm not ready yet.",ar:"أنا مش جاهز لسه.",note:"تأجيل"},
{id:102,en:"Give me another chance.",ar:"اديني فرصة تانية.",note:"طلب"},
{id:103,en:"I totally forgot.",ar:"أنا نسيت خالص.",note:"نسيان"},
{id:104,en:"That makes sense.",ar:"ده منطقي.",note:"اتفاق"},
{id:105,en:"I changed my mind.",ar:"غيرت رأيي.",note:"قرار"},
{id:106,en:"It's up to you.",ar:"القرار يرجعلك.",note:"اختيار"},
{id:107,en:"I don't feel well.",ar:"أنا مش حاسس إني كويس.",note:"صحة"},
{id:108,en:"I need some fresh air.",ar:"محتاج شوية هوا.",note:"راحة"},
{id:109,en:"Can you hear me?",ar:"إنت سامعني؟",note:"اتصال"},
{id:110,en:"The connection is bad.",ar:"الاتصال وحش.",note:"مكالمة"},

{id:111,en:"I can't hear you clearly.",ar:"مش سامعك كويس.",note:"مكالمة"},
{id:112,en:"Your voice is breaking up.",ar:"صوتك بيقطع.",note:"مكالمة"},
{id:113,en:"Hold on a second.",ar:"استنى ثانية.",note:"انتظار"},
{id:114,en:"I'm almost done.",ar:"أنا قربت أخلص.",note:"وقت"},
{id:115,en:"Let's do it together.",ar:"نعملها سوا.",note:"تعاون"},
{id:116,en:"I need more time.",ar:"محتاج وقت أكتر.",note:"وقت"},
{id:117,en:"This is difficult.",ar:"ده صعب.",note:"وصف"},
{id:118,en:"This is easy.",ar:"ده سهل.",note:"وصف"},
{id:119,en:"I can handle it.",ar:"أقدر أتعامل معاه.",note:"ثقة"},
{id:120,en:"Everything is under control.",ar:"كل حاجة تحت السيطرة.",note:"طمأنة"},

{id:121,en:"I feel nervous.",ar:"حاسس بتوتر.",note:"مشاعر"},
{id:122,en:"Take a deep breath.",ar:"خد نفس عميق.",note:"تهدئة"},
{id:123,en:"You can do it.",ar:"إنت تقدر تعملها.",note:"تشجيع"},
{id:124,en:"Believe in yourself.",ar:"ثق في نفسك.",note:"تحفيز"},
{id:125,en:"Don't give up.",ar:"ما تستسلمش.",note:"تحفيز"},
{id:126,en:"Keep going.",ar:"كمل.",note:"تشجيع"},
{id:127,en:"I trust your opinion.",ar:"أنا بثق في رأيك.",note:"ثقة"},
{id:128,en:"What do you recommend?",ar:"إيه اللي تنصح بيه؟",note:"طلب رأي"},
{id:129,en:"I will think about it.",ar:"هفكر في الموضوع.",note:"تفكير"},
{id:130,en:"That sounds great.",ar:"ده شكله ممتاز.",note:"إعجاب"},

{id:131,en:"I'm not sure.",ar:"أنا مش متأكد.",note:"تردد"},
{id:132,en:"Maybe later.",ar:"يمكن بعدين.",note:"تأجيل"},
{id:133,en:"Let's see what happens.",ar:"نشوف هيحصل إيه.",note:"ترقب"},
{id:134,en:"I wasn't expecting that.",ar:"ماكنتش متوقع ده.",note:"مفاجأة"},
{id:135,en:"That's interesting.",ar:"ده مثير للاهتمام.",note:"اهتمام"},
{id:136,en:"That's unbelievable.",ar:"ده مش معقول.",note:"تعجب"},
{id:137,en:"What a surprise!",ar:"يا للمفاجأة!",note:"مفاجأة"},
{id:138,en:"You scared me.",ar:"خضتني.",note:"موقف"},
{id:139,en:"It's not a big deal.",ar:"مش مشكلة كبيرة.",note:"تهوين"},
{id:140,en:"Forget about it.",ar:"انسى الموضوع.",note:"تجاوز"},

{id:141,en:"I appreciate your honesty.",ar:"أقدر صراحتك.",note:"تقدير"},
{id:142,en:"Thanks for understanding.",ar:"شكرًا لتفهمك.",note:"شكر"},
{id:143,en:"I owe you one.",ar:"أنا مديونلك بواحدة.",note:"امتنان"},
{id:144,en:"No need to apologize.",ar:"مفيش داعي للاعتذار.",note:"تسامح"},
{id:145,en:"It wasn't your fault.",ar:"مش غلطتك.",note:"دعم"},
{id:146,en:"Everyone makes mistakes.",ar:"كل الناس بتغلط.",note:"طمأنة"},
{id:147,en:"Learn from your mistakes.",ar:"اتعلم من أخطائك.",note:"نصيحة"},
{id:148,en:"I need a break.",ar:"محتاج بريك.",note:"راحة"},
{id:149,en:"Let's take a walk.",ar:"يلا نتمشى.",note:"اقتراح"},
{id:150,en:"I need some silence.",ar:"محتاج شوية هدوء.",note:"راحة"},

{id:151,en:"Can you keep a secret?",ar:"ممكن تحتفظ بسر؟",note:"سر"},
{id:152,en:"Don't tell anyone.",ar:"ما تقولش لحد.",note:"سر"},
{id:153,en:"I promise.",ar:"أوعدك.",note:"وعد"},
{id:154,en:"Trust me.",ar:"ثق فيا.",note:"ثقة"},
{id:155,en:"I'm telling the truth.",ar:"أنا بقول الحقيقة.",note:"تأكيد"},
{id:156,en:"Why are you laughing?",ar:"إنت بتضحك ليه؟",note:"سؤال"},
{id:157,en:"I'm just joking.",ar:"أنا بهزر بس.",note:"مزاح"},
{id:158,en:"Seriously?",ar:"بجد؟",note:"تعجب"},
{id:159,en:"You must be kidding.",ar:"أكيد بتهزر.",note:"عدم تصديق"},
{id:160,en:"That's hilarious.",ar:"دي مضحكة جدًا.",note:"ضحك"},

{id:161,en:"I feel embarrassed.",ar:"حاسس بإحراج.",note:"مشاعر"},
{id:162,en:"It happens sometimes.",ar:"بتحصل أحيانًا.",note:"طمأنة"},
{id:163,en:"Don't blame yourself.",ar:"ما تلومش نفسك.",note:"دعم"},
{id:164,en:"I'm proud of you.",ar:"أنا فخور بيك.",note:"تشجيع"},
{id:165,en:"You did a great job.",ar:"إنت عملت شغل ممتاز.",note:"مدح"},
{id:166,en:"I respect you.",ar:"أنا بحترمك.",note:"احترام"},
{id:167,en:"That was very kind.",ar:"ده كان لطف منك.",note:"امتنان"},
{id:168,en:"Can I trust you?",ar:"أقدر أثق فيك؟",note:"ثقة"},
{id:169,en:"Please be honest with me.",ar:"خليك صريح معايا.",note:"صراحة"},
{id:170,en:"I understand your situation.",ar:"أنا فاهم موقفك.",note:"تفهم"},

{id:171,en:"Let's stay positive.",ar:"خلينا إيجابيين.",note:"تحفيز"},
{id:172,en:"Things will improve.",ar:"الأمور هتتحسن.",note:"تفاؤل"},
{id:173,en:"I'm trying my best.",ar:"أنا بحاول بأقصى جهدي.",note:"مجهود"},
{id:174,en:"That's enough for today.",ar:"كفاية النهارده.",note:"توقف"},
{id:175,en:"Tomorrow is another day.",ar:"بكرة يوم جديد.",note:"تفاؤل"},
{id:176,en:"I need to focus.",ar:"محتاج أركز.",note:"تركيز"},
{id:177,en:"Don't distract me.",ar:"ما تشتتنيش.",note:"تركيز"},
{id:178,en:"I can't concentrate.",ar:"مش قادر أركز.",note:"تركيز"},
{id:179,en:"Let's fix this problem.",ar:"يلا نحل المشكلة دي.",note:"حل مشاكل"},
{id:180,en:"We need a solution.",ar:"إحنا محتاجين حل.",note:"حل مشاكل"},

{id:181,en:"This is urgent.",ar:"ده ضروري جدًا.",note:"استعجال"},
{id:182,en:"Call me immediately.",ar:"كلمني فورًا.",note:"استعجال"},
{id:183,en:"I will be there soon.",ar:"هكون هناك قريب.",note:"وصول"},
{id:184,en:"I'm running late.",ar:"أنا متأخر.",note:"وقت"},
{id:185,en:"Traffic is terrible.",ar:"الزحمة فظيعة.",note:"مواصلات"},
{id:186,en:"The place is crowded.",ar:"المكان زحمة.",note:"مكان"},
{id:187,en:"I can't find parking.",ar:"مش لاقي ركنة.",note:"سيارة"},
{id:188,en:"Let's meet outside.",ar:"نتقابل بره.",note:"مقابلة"},
{id:189,en:"I'm waiting for you.",ar:"أنا مستنيك.",note:"انتظار"},
{id:190,en:"Where have you been?",ar:"إنت كنت فين؟",note:"سؤال"},

{id:191,en:"I had a long day.",ar:"كان يوم طويل.",note:"تعب"},
{id:192,en:"I need some sleep.",ar:"محتاج أنام شوية.",note:"راحة"},
{id:193,en:"I'm exhausted.",ar:"أنا مرهق جدًا.",note:"تعب"},
{id:194,en:"Let's relax.",ar:"يلا نسترخي.",note:"راحة"},
{id:195,en:"Turn off the lights.",ar:"اطفي النور.",note:"منزل"},
{id:196,en:"Close the door, please.",ar:"اقفل الباب لو سمحت.",note:"منزل"},
{id:197,en:"Open the window.",ar:"افتح الشباك.",note:"منزل"},
{id:198,en:"It's too hot here.",ar:"الجو حر هنا.",note:"طقس"},
{id:199,en:"It's really cold today.",ar:"الدنيا برد النهارده.",note:"طقس"},
{id:200,en:"I hope everything goes well.",ar:"أتمنى كل حاجة تمشي كويس.",note:"أمل"},
{id:201,en:"I woke up late today.",ar:"صحيت متأخر النهارده.",note:"روتين يومي"},
{id:202,en:"I missed the bus.",ar:"فاتني الأوتوبيس.",note:"مواصلات"},
{id:203,en:"I need to hurry.",ar:"لازم أستعجل.",note:"وقت"},
{id:204,en:"I'm stuck in traffic.",ar:"أنا واقف في الزحمة.",note:"مواصلات"},
{id:205,en:"The road is blocked.",ar:"الطريق مقفول.",note:"مواصلات"},
{id:206,en:"Can you pick me up?",ar:"ممكن تيجي تاخدني؟",note:"طلب"},
{id:207,en:"I'll send you my location.",ar:"هبعتلك اللوكيشن.",note:"موقع"},
{id:208,en:"My phone is about to die.",ar:"موبايلي قرب يفصل.",note:"هاتف"},
{id:209,en:"I forgot my password.",ar:"نسيت الباسورد.",note:"تكنولوجيا"},
{id:210,en:"The app keeps crashing.",ar:"التطبيق بيفصل باستمرار.",note:"تكنولوجيا"},

{id:211,en:"I need to recharge my phone.",ar:"محتاج أشحن موبايلي.",note:"هاتف"},
{id:212,en:"The signal is weak.",ar:"الإشارة ضعيفة.",note:"اتصال"},
{id:213,en:"I can't connect to the internet.",ar:"مش عارف أوصل للإنترنت.",note:"إنترنت"},
{id:214,en:"Try restarting it.",ar:"جرّب تعيد تشغيله.",note:"حل مشكلة"},
{id:215,en:"It's finally working now.",ar:"اشتغل أخيرًا دلوقتي.",note:"حل مشكلة"},
{id:216,en:"I need a favor.",ar:"محتاج خدمة.",note:"طلب"},
{id:217,en:"Can you do me a favor?",ar:"ممكن تعملي خدمة؟",note:"طلب"},
{id:218,en:"Sure, no problem.",ar:"أكيد، مفيش مشكلة.",note:"موافقة"},
{id:219,en:"I really appreciate it.",ar:"أنا مقدر ده جدًا.",note:"امتنان"},
{id:220,en:"You saved me.",ar:"إنت أنقذتني.",note:"شكر"},

{id:221,en:"I didn't expect this.",ar:"ماكنتش متوقع ده.",note:"مفاجأة"},
{id:222,en:"That's unbelievable.",ar:"ده لا يصدق.",note:"تعجب"},
{id:223,en:"I can't believe it.",ar:"مش مصدق.",note:"تعجب"},
{id:224,en:"What a coincidence!",ar:"يا للصدفة!",note:"موقف"},
{id:225,en:"This is getting weird.",ar:"الموضوع بقى غريب.",note:"تعجب"},
{id:226,en:"Something feels wrong.",ar:"حاسس إن في حاجة غلط.",note:"إحساس"},
{id:227,en:"I have a bad feeling.",ar:"عندي إحساس وحش.",note:"مشاعر"},
{id:228,en:"Don't overthink it.",ar:"ما تفكرش زيادة.",note:"نصيحة"},
{id:229,en:"Just relax.",ar:"بس اهدى.",note:"تهدئة"},
{id:230,en:"Everything happens for a reason.",ar:"كل حاجة بتحصل لسبب.",note:"فلسفة"},

{id:231,en:"Let's change the subject.",ar:"خلينا نغير الموضوع.",note:"محادثة"},
{id:232,en:"That's none of my business.",ar:"دي مش مشكلتي.",note:"تدخل"},
{id:233,en:"Mind your own business.",ar:"خليك في حالك.",note:"حدود"},
{id:234,en:"I didn't mean that.",ar:"ماكنتش أقصد كده.",note:"توضيح"},
{id:235,en:"You misunderstood me.",ar:"إنت فهمتني غلط.",note:"توضيح"},
{id:236,en:"Let me explain.",ar:"خليني أوضح.",note:"شرح"},
{id:237,en:"Now I understand.",ar:"دلوقتي فهمت.",note:"فهم"},
{id:238,en:"That makes more sense.",ar:"كده منطقي أكتر.",note:"فهم"},
{id:239,en:"You're absolutely right.",ar:"إنت معاك حق تمامًا.",note:"اتفاق"},
{id:240,en:"I completely disagree.",ar:"أنا مختلف تمامًا.",note:"اختلاف"},

{id:241,en:"Let's not argue.",ar:"بلاش نتخانق.",note:"تهدئة"},
{id:242,en:"Calm down and listen.",ar:"اهدى واسمع.",note:"تهدئة"},
{id:243,en:"I didn't say that.",ar:"أنا ماقولتش كده.",note:"دفاع"},
{id:244,en:"You're taking it personally.",ar:"إنت واخد الموضوع بشكل شخصي.",note:"نقاش"},
{id:245,en:"Forget what I said.",ar:"انسَ اللي قولته.",note:"تراجع"},
{id:246,en:"I need some space.",ar:"محتاج شوية مساحة.",note:"مشاعر"},
{id:247,en:"Leave me alone for a while.",ar:"سيبني لوحدي شوية.",note:"خصوصية"},
{id:248,en:"I'm trying to stay calm.",ar:"بحاول أهدى.",note:"مشاعر"},
{id:249,en:"This situation is stressful.",ar:"الموقف ده متعب.",note:"ضغط"},
{id:250,en:"I'm mentally exhausted.",ar:"أنا مرهق نفسيًا.",note:"تعب"},

{id:251,en:"Let's grab some coffee.",ar:"يلا نجيب قهوة.",note:"خروجة"},
{id:252,en:"I'm craving something sweet.",ar:"نفسي في حاجة حلوة.",note:"طعام"},
{id:253,en:"Let's order food.",ar:"يلا نطلب أكل.",note:"طعام"},
{id:254,en:"What do you want to eat?",ar:"عايز تاكل إيه؟",note:"طعام"},
{id:255,en:"I'm not hungry anymore.",ar:"أنا مش جعان دلوقتي.",note:"طعام"},
{id:256,en:"This tastes amazing.",ar:"طعمه رهيب.",note:"طعام"},
{id:257,en:"It's too salty.",ar:"مالح زيادة.",note:"طعام"},
{id:258,en:"It's too spicy.",ar:"حرّاق زيادة.",note:"طعام"},
{id:259,en:"Can I get some water?",ar:"ممكن شوية مية؟",note:"طلب"},
{id:260,en:"I'm full.",ar:"أنا شبعت.",note:"طعام"},

{id:261,en:"I need to save money.",ar:"لازم أوفر فلوس.",note:"مال"},
{id:262,en:"I'm broke right now.",ar:"أنا مفلس دلوقتي.",note:"مال"},
{id:263,en:"Can you lend me some money?",ar:"ممكن تسلفني شوية فلوس؟",note:"مال"},
{id:264,en:"I'll pay you back later.",ar:"هرجعهالك بعدين.",note:"مال"},
{id:265,en:"I spent too much today.",ar:"صرفت كتير النهارده.",note:"مال"},
{id:266,en:"This is worth it.",ar:"ده يستاهل.",note:"شراء"},
{id:267,en:"I found a cheaper option.",ar:"لقيت خيار أرخص.",note:"شراء"},
{id:268,en:"Let's split the bill.",ar:"نقسم الحساب.",note:"دفع"},
{id:269,en:"I forgot my wallet at home.",ar:"نسيت المحفظة في البيت.",note:"نسيان"},
{id:270,en:"Can you cover me this time?",ar:"ممكن تحاسب المرة دي؟",note:"مال"},

{id:271,en:"I need motivation.",ar:"محتاج تحفيز.",note:"تحفيز"},
{id:272,en:"I'm losing focus.",ar:"بدأت أفقد تركيزي.",note:"تركيز"},
{id:273,en:"Stay focused on your goals.",ar:"ركز على أهدافك.",note:"تحفيز"},
{id:274,en:"Hard work pays off.",ar:"التعب بيجيب نتيجة.",note:"تحفيز"},
{id:275,en:"Success takes patience.",ar:"النجاح يحتاج صبر.",note:"تحفيز"},
{id:276,en:"Don't compare yourself to others.",ar:"ما تقارنش نفسك بحد.",note:"تطوير"},
{id:277,en:"Everyone has their own journey.",ar:"كل واحد له رحلته.",note:"تطوير"},
{id:278,en:"Believe in the process.",ar:"ثق في الرحلة.",note:"تحفيز"},
{id:279,en:"Small progress is still progress.",ar:"التقدم البسيط يعتبر تقدم.",note:"تحفيز"},
{id:280,en:"Keep improving yourself.",ar:"استمر في تطوير نفسك.",note:"تطوير"},

{id:281,en:"I need to organize my time.",ar:"محتاج أنظم وقتي.",note:"تنظيم"},
{id:282,en:"I'm always distracted.",ar:"أنا دايمًا مشتت.",note:"تركيز"},
{id:283,en:"I have too much to do.",ar:"عندي حاجات كتير أعملها.",note:"ضغط"},
{id:284,en:"One step at a time.",ar:"خطوة خطوة.",note:"تحفيز"},
{id:285,en:"Let's make a plan.",ar:"يلا نحط خطة.",note:"تنظيم"},
{id:286,en:"Write it down.",ar:"اكتبها.",note:"تنظيم"},
{id:287,en:"Don't forget the details.",ar:"ما تنساش التفاصيل.",note:"تنظيم"},
{id:288,en:"Double-check everything.",ar:"راجع كل حاجة مرتين.",note:"تنظيم"},
{id:289,en:"Preparation is important.",ar:"التحضير مهم.",note:"تطوير"},
{id:290,en:"Timing is everything.",ar:"التوقيت مهم جدًا.",note:"وقت"},

{id:291,en:"I need some inspiration.",ar:"محتاج إلهام.",note:"تحفيز"},
{id:292,en:"This motivates me.",ar:"ده بيحفزني.",note:"تحفيز"},
{id:293,en:"I learned something new today.",ar:"اتعلمت حاجة جديدة النهارده.",note:"تعلم"},
{id:294,en:"Knowledge is power.",ar:"المعرفة قوة.",note:"تعلم"},
{id:295,en:"Experience teaches everything.",ar:"الخبرة بتعلم كل حاجة.",note:"خبرة"},
{id:296,en:"Mistakes help us grow.",ar:"الأخطاء بتساعدنا نتطور.",note:"تعلم"},
{id:297,en:"I won't repeat that mistake.",ar:"مش هكرر الغلطة دي.",note:"تعلم"},
{id:298,en:"Life is teaching me lessons.",ar:"الحياة بتعلمني دروس.",note:"حياة"},
{id:299,en:"Every day is a new chance.",ar:"كل يوم فرصة جديدة.",note:"تفاؤل"},
{id:300,en:"I'm ready for the next step.",ar:"أنا جاهز للخطوة الجاية.",note:"تطوير"},
],

"daily":[],
"restaurants":[],
"work":[],
"travel":[],
"social":[],
"relationships":[],
"business":[],
"pronunciation":[]

};
