const phraseModules = {

"real-life":[

{id:1,en:"Can you help me, please?",ar:"ممكن تساعدني لو سمحت؟",note:"طلب مساعدة"},
{id:2,en:"I need some help.",ar:"أنا محتاج مساعدة.",note:"طلب مساعدة"},
{id:3,en:"Please wait a moment.",ar:"استنى لحظة لو سمحت.",note:"طلب وقت"},
{id:4,en:"I have a problem.",ar:"عندي مشكلة.",note:"شرح موقف"},
{id:5,en:"What should I do?",ar:"أعمل إيه؟",note:"طلب نصيحة"},
{id:6,en:"I don't understand.",ar:"أنا مش فاهم.",note:"عدم فهم"},
{id:7,en:"Can you repeat that?",ar:"ممكن تعيد؟",note:"طلب إعادة"},
{id:8,en:"Speak slowly, please.",ar:"اتكلم ببطء لو سمحت.",note:"مساعدة في الفهم"},
{id:9,en:"I am lost.",ar:"أنا تايه.",note:"اتجاهات"},
{id:10,en:"Where am I?",ar:"أنا فين؟",note:"اتجاهات"},

{id:11,en:"Can you show me the way?",ar:"ممكن تدلني على الطريق؟",note:"طلب اتجاهات"},
{id:12,en:"I forgot my phone.",ar:"نسيت موبايلي.",note:"موقف يومي"},
{id:13,en:"My battery is dead.",ar:"البطارية فصلت.",note:"تكنولوجيا"},
{id:14,en:"I need a charger.",ar:"محتاج شاحن.",note:"طلب شيء"},
{id:15,en:"Do you have Wi-Fi?",ar:"عندكم واي فاي؟",note:"إنترنت"},
{id:16,en:"What's the password?",ar:"إيه الباسورد؟",note:"إنترنت"},
{id:17,en:"I can't open it.",ar:"مش عارف أفتحه.",note:"مشكلة"},
{id:18,en:"It's not working.",ar:"مش شغال.",note:"عطل"},
{id:19,en:"Try again.",ar:"حاول تاني.",note:"تشجيع"},
{id:20,en:"Don't worry.",ar:"متقلقش.",note:"طمأنة"},

{id:21,en:"Everything is okay.",ar:"كل حاجة تمام.",note:"طمأنة"},
{id:22,en:"Take your time.",ar:"خد وقتك.",note:"هدوء"},
{id:23,en:"I'm in a hurry.",ar:"أنا مستعجل.",note:"وقت"},
{id:24,en:"Let's go now.",ar:"يلا بينا دلوقتي.",note:"حركة"},
{id:25,en:"Wait here.",ar:"استنى هنا.",note:"تعليمات"},
{id:26,en:"Follow me.",ar:"امشي ورايا.",note:"اتجاهات"},
{id:27,en:"Be careful.",ar:"خلي بالك.",note:"تحذير"},
{id:28,en:"Watch your step.",ar:"خلي بالك وإنت ماشي.",note:"تحذير"},
{id:29,en:"I feel sick.",ar:"حاسس إني تعبان.",note:"صحة"},
{id:30,en:"I need a doctor.",ar:"محتاج دكتور.",note:"طوارئ"},

{id:31,en:"Call the police.",ar:"اتصل بالشرطة.",note:"طوارئ"},
{id:32,en:"Call an ambulance.",ar:"هات إسعاف.",note:"طوارئ"},
{id:33,en:"I lost my wallet.",ar:"محفظتي ضاعت.",note:"مشكلة"},
{id:34,en:"Someone stole my bag.",ar:"حد سرق شنطتي.",note:"سرقة"},
{id:35,en:"Can I use your phone?",ar:"ممكن أستخدم تليفونك؟",note:"طلب"},
{id:36,en:"I need some cash.",ar:"محتاج كاش.",note:"فلوس"},
{id:37,en:"Where is the ATM?",ar:"فين الـ ATM؟",note:"بنك"},
{id:38,en:"I don't have enough money.",ar:"معيش فلوس كفاية.",note:"فلوس"},
{id:39,en:"Can I pay by card?",ar:"ينفع أدفع كارت؟",note:"دفع"},
{id:40,en:"The price is too high.",ar:"السعر غالي جدًا.",note:"شراء"},

{id:41,en:"Can you lower the price?",ar:"ممكن تقلل السعر؟",note:"تفاوض"},
{id:42,en:"That's expensive.",ar:"ده غالي.",note:"شراء"},
{id:43,en:"That's cheap.",ar:"ده رخيص.",note:"شراء"},
{id:44,en:"I like this one.",ar:"عجبني ده.",note:"اختيار"},
{id:45,en:"Do you have another color?",ar:"عندك لون تاني؟",note:"تسوق"},
{id:46,en:"What size is this?",ar:"المقاس ده كام؟",note:"ملابس"},
{id:47,en:"It's too small.",ar:"ده صغير أوي.",note:"مقاسات"},
{id:48,en:"It's too big.",ar:"ده كبير أوي.",note:"مقاسات"},
{id:49,en:"Can I try it?",ar:"ممكن أقيسه؟",note:"تجربة"},
{id:50,en:"I will take it.",ar:"هاخده.",note:"شراء"},

{id:51,en:"I'm tired.",ar:"أنا تعبان.",note:"مشاعر"},
{id:52,en:"I need some rest.",ar:"محتاج أرتاح شوية.",note:"راحة"},
{id:53,en:"I feel better now.",ar:"حاسس إني أحسن دلوقتي.",note:"تحسن"},
{id:54,en:"I'm hungry.",ar:"أنا جعان.",note:"طعام"},
{id:55,en:"I'm thirsty.",ar:"أنا عطشان.",note:"طعام"},
{id:56,en:"Let's eat something.",ar:"يلا ناكل حاجة.",note:"طعام"},
{id:57,en:"I'm bored.",ar:"أنا زهقان.",note:"مشاعر"},
{id:58,en:"I'm happy today.",ar:"أنا مبسوط النهارده.",note:"مشاعر"},
{id:59,en:"I feel stressed.",ar:"حاسس بضغط.",note:"مشاعر"},
{id:60,en:"Calm down.",ar:"اهدى.",note:"تهدئة"},

{id:61,en:"I miss you.",ar:"إنت واحشني.",note:"علاقات"},
{id:62,en:"I trust you.",ar:"أنا بثق فيك.",note:"علاقات"},
{id:63,en:"Tell me the truth.",ar:"قولّي الحقيقة.",note:"حديث"},
{id:64,en:"I don't believe you.",ar:"أنا مش مصدقك.",note:"شك"},
{id:65,en:"I'm serious.",ar:"أنا بتكلم بجد.",note:"تأكيد"},
{id:66,en:"Are you kidding?",ar:"إنت بتهزر؟",note:"تعجب"},
{id:67,en:"That was funny.",ar:"دي كانت مضحكة.",note:"ضحك"},
{id:68,en:"What happened?",ar:"إيه اللي حصل؟",note:"سؤال"},
{id:69,en:"Nothing happened.",ar:"محصلش حاجة.",note:"رد"},
{id:70,en:"It's my fault.",ar:"ده غلطي.",note:"اعتراف"},

{id:71,en:"I'm sorry.",ar:"أنا آسف.",note:"اعتذار"},
{id:72,en:"No problem.",ar:"مفيش مشكلة.",note:"رد"},
{id:73,en:"Thank you so much.",ar:"شكراً جدًا.",note:"شكر"},
{id:74,en:"You're welcome.",ar:"العفو.",note:"رد"},
{id:75,en:"Excuse me.",ar:"لو سمحت.",note:"استئذان"},
{id:76,en:"Can I ask you something?",ar:"ممكن أسألك حاجة؟",note:"سؤال"},
{id:77,en:"Of course.",ar:"طبعًا.",note:"موافقة"},
{id:78,en:"I agree with you.",ar:"أنا متفق معاك.",note:"اتفاق"},
{id:79,en:"I don't agree.",ar:"أنا مش متفق.",note:"اختلاف"},
{id:80,en:"Maybe you're right.",ar:"يمكن معاك حق.",note:"رأي"},

{id:81,en:"Let's talk later.",ar:"نتكلم بعدين.",note:"تأجيل"},
{id:82,en:"I'm busy right now.",ar:"أنا مشغول دلوقتي.",note:"انشغال"},
{id:83,en:"Call me later.",ar:"كلمني بعدين.",note:"اتصال"},
{id:84,en:"Send me the address.",ar:"ابعتلي العنوان.",note:"معلومات"},
{id:85,en:"I'm outside.",ar:"أنا بره.",note:"مكان"},
{id:86,en:"I'm coming.",ar:"أنا جاي.",note:"حركة"},
{id:87,en:"I'm almost there.",ar:"أنا قربت أوصل.",note:"حركة"},
{id:88,en:"I just arrived.",ar:"لسه واصل حالًا.",note:"وصول"},
{id:89,en:"See you tomorrow.",ar:"أشوفك بكرة.",note:"وداع"},
{id:90,en:"Take care of yourself.",ar:"خلي بالك من نفسك.",note:"اهتمام"},

{id:91,en:"Good luck.",ar:"بالتوفيق.",note:"تشجيع"},
{id:92,en:"Congratulations!",ar:"مبروك!",note:"تهنئة"},
{id:93,en:"Happy birthday!",ar:"عيد ميلاد سعيد!",note:"مناسبة"},
{id:94,en:"Enjoy your day.",ar:"استمتع بيومك.",note:"إيجابية"},
{id:95,en:"Have a safe trip.",ar:"رحلة سعيدة.",note:"سفر"},
{id:96,en:"Drive safely.",ar:"اسوق بالراحة.",note:"تحذير"},
{id:97,en:"See you soon.",ar:"أشوفك قريب.",note:"وداع"},
{id:98,en:"Text me when you arrive.",ar:"ابعتلي لما توصل.",note:"متابعة"},
{id:99,en:"I appreciate your help.",ar:"مقدر مساعدتك.",note:"شكر"},
{id:100,en:"Everything will be fine.",ar:"كل حاجة هتبقى تمام.",note:"طمأنة"}

],

"daily":[],
"restaurants":[],
"work":[],
"travel":[],
"social":[],
"relationships":[],
"business":[],
"pronunciation":[]

};
