const phraseModules = {

"real-life":[

{id:1,en:"Can you help me, please?",ar:"ممكن تساعدني لو سمحت؟",note:"طلب مساعدة"},
{id:2,en:"I need some help.",ar:"أنا محتاج مساعدة.",note:"طلب مساعدة"},
{id:3,en:"Please wait a moment.",ar:"استنى لحظة لو سمحت.",note:"طلب وقت"},
{id:4,en:"I have a problem.",ar:"عندي مشكلة.",note:"شرح موقف"},
{id:5,en:"What should I do?",ar:"أعمل إيه؟",note:"طلب نصيحة"},
{id:6,en:"I don't understand.",ar:"أنا مش فاهم.",note:"عدم فهم"},
{id:7,en:"Can you repeat that?",ar:"ممكن تعيد؟",note:"طلب إعادة"},
{id:8,en:"Speak slowly, please.",ar:"اتكلم ببطء لو سمحت.",note:"مساعدة في الفهم"},
{id:9,en:"I am lost.",ar:"أنا تايه.",note:"اتجاهات"},
{id:10,en:"Where am I?",ar:"أنا فين؟",note:"اتجاهات"},

{id:11,en:"Can you show me the way?",ar:"ممكن تدلني على الطريق؟",note:"طلب اتجاهات"},
{id:12,en:"I forgot my phone.",ar:"نسيت موبايلي.",note:"موقف يومي"},
{id:13,en:"My battery is dead.",ar:"البطارية فصلت.",note:"تكنولوجيا"},
{id:14,en:"I need a charger.",ar:"محتاج شاحن.",note:"طلب شيء"},
{id:15,en:"Do you have Wi-Fi?",ar:"عندكم واي فاي؟",note:"إنترنت"},
{id:16,en:"What's the password?",ar:"إيه الباسورد؟",note:"إنترنت"},
{id:17,en:"I can't open it.",ar:"مش عارف أفتحه.",note:"مشكلة"},
{id:18,en:"It's not working.",ar:"مش شغال.",note:"عطل"},
{id:19,en:"Try again.",ar:"حاول تاني.",note:"تشجيع"},
{id:20,en:"Don't worry.",ar:"متقلقش.",note:"طمأنة"},

{id:21,en:"Everything is okay.",ar:"كل حاجة تمام.",note:"طمأنة"},
{id:22,en:"Take your time.",ar:"خد وقتك.",note:"هدوء"},
{id:23,en:"I'm in a hurry.",ar:"أنا مستعجل.",note:"وقت"},
{id:24,en:"Let's go now.",ar:"يلا بينا دلوقتي.",note:"حركة"},
{id:25,en:"Wait here.",ar:"استنى هنا.",note:"تعليمات"},
{id:26,en:"Follow me.",ar:"امشي ورايا.",note:"اتجاهات"},
{id:27,en:"Be careful.",ar:"خلي بالك.",note:"تحذير"},
{id:28,en:"Watch your step.",ar:"خلي بالك وإنت ماشي.",note:"تحذير"},
{id:29,en:"I feel sick.",ar:"حاسس إني تعبان.",note:"صحة"},
{id:30,en:"I need a doctor.",ar:"محتاج دكتور.",note:"طوارئ"},

{id:31,en:"Call the police.",ar:"اتصل بالشرطة.",note:"طوارئ"},
{id:32,en:"Call an ambulance.",ar:"هات إسعاف.",note:"طوارئ"},
{id:33,en:"I lost my wallet.",ar:"محفظتي ضاعت.",note:"مشكلة"},
{id:34,en:"Someone stole my bag.",ar:"حد سرق شنطتي.",note:"سرقة"},
{id:35,en:"Can I use your phone?",ar:"ممكن أستخدم تليفونك؟",note:"طلب"},
{id:36,en:"I need some cash.",ar:"محتاج كاش.",note:"فلوس"},
{id:37,en:"Where is the ATM?",ar:"فين الـ ATM؟",note:"بنك"},
{id:38,en:"I don't have enough money.",ar:"معيش فلوس كفاية.",note:"فلوس"},
{id:39,en:"Can I pay by card?",ar:"ينفع أدفع كارت؟",note:"دفع"},
{id:40,en:"The price is too high.",ar:"السعر غالي جدًا.",note:"شراء"},

{id:41,en:"Can you lower the price?",ar:"ممكن تقلل السعر؟",note:"تفاوض"},
{id:42,en:"That's expensive.",ar:"ده غالي.",note:"شراء"},
{id:43,en:"That's cheap.",ar:"ده رخيص.",note:"شراء"},
{id:44,en:"I like this one.",ar:"عجبني ده.",note:"اختيار"},
{id:45,en:"Do you have another color?",ar:"عندك لون تاني؟",note:"تسوق"},
{id:46,en:"What size is this?",ar:"المقاس ده كام؟",note:"ملابس"},
{id:47,en:"It's too small.",ar:"ده صغير أوي.",note:"مقاسات"},
{id:48,en:"It's too big.",ar:"ده كبير أوي.",note:"مقاسات"},
{id:49,en:"Can I try it?",ar:"ممكن أقيسه؟",note:"تجربة"},
{id:50,en:"I will take it.",ar:"هاخده.",note:"شراء"},

{id:51,en:"I'm tired.",ar:"أنا تعبان.",note:"مشاعر"},
{id:52,en:"I need some rest.",ar:"محتاج أرتاح شوية.",note:"راحة"},
{id:53,en:"I feel better now.",ar:"حاسس إني أحسن دلوقتي.",note:"تحسن"},
{id:54,en:"I'm hungry.",ar:"أنا جعان.",note:"طعام"},
{id:55,en:"I'm thirsty.",ar:"أنا عطشان.",note:"طعام"},
{id:56,en:"Let's eat something.",ar:"يلا ناكل حاجة.",note:"طعام"},
{id:57,en:"I'm bored.",ar:"أنا زهقان.",note:"مشاعر"},
{id:58,en:"I'm happy today.",ar:"أنا مبسوط النهارده.",note:"مشاعر"},
{id:59,en:"I feel stressed.",ar:"حاسس بضغط.",note:"مشاعر"},
{id:60,en:"Calm down.",ar:"اهدى.",note:"تهدئة"},

{id:61,en:"I miss you.",ar:"إنت واحشني.",note:"علاقات"},
{id:62,en:"I trust you.",ar:"أنا بثق فيك.",note:"علاقات"},
{id:63,en:"Tell me the truth.",ar:"قولّي الحقيقة.",note:"حديث"},
{id:64,en:"I don't believe you.",ar:"أنا مش مصدقك.",note:"شك"},
{id:65,en:"I'm serious.",ar:"أنا بتكلم بجد.",note:"تأكيد"},
{id:66,en:"Are you kidding?",ar:"إنت بتهزر؟",note:"تعجب"},
{id:67,en:"That was funny.",ar:"دي كانت مضحكة.",note:"ضحك"},
{id:68,en:"What happened?",ar:"إيه اللي حصل؟",note:"سؤال"},
{id:69,en:"Nothing happened.",ar:"محصلش حاجة.",note:"رد"},
{id:70,en:"It's my fault.",ar:"ده غلطي.",note:"اعتراف"},

{id:71,en:"I'm sorry.",ar:"أنا آسف.",note:"اعتذار"},
{id:72,en:"No problem.",ar:"مفيش مشكلة.",note:"رد"},
{id:73,en:"Thank you so much.",ar:"شكراً جدًا.",note:"شكر"},
{id:74,en:"You're welcome.",ar:"العفو.",note:"رد"},
{id:75,en:"Excuse me.",ar:"لو سمحت.",note:"استئذان"},
{id:76,en:"Can I ask you something?",ar:"ممكن أسألك حاجة؟",note:"سؤال"},
{id:77,en:"Of course.",ar:"طبعًا.",note:"موافقة"},
{id:78,en:"I agree with you.",ar:"أنا متفق معاك.",note:"اتفاق"},
{id:79,en:"I don't agree.",ar:"أنا مش متفق.",note:"اختلاف"},
{id:80,en:"Maybe you're right.",ar:"يمكن معاك حق.",note:"رأي"},

{id:81,en:"Let's talk later.",ar:"نتكلم بعدين.",note:"تأجيل"},
{id:82,en:"I'm busy right now.",ar:"أنا مشغول دلوقتي.",note:"انشغال"},
{id:83,en:"Call me later.",ar:"كلمني بعدين.",note:"اتصال"},
{id:84,en:"Send me the address.",ar:"ابعتلي العنوان.",note:"معلومات"},
{id:85,en:"I'm outside.",ar:"أنا بره.",note:"مكان"},
{id:86,en:"I'm coming.",ar:"أنا جاي.",note:"حركة"},
{id:87,en:"I'm almost there.",ar:"أنا قربت أوصل.",note:"حركة"},
{id:88,en:"I just arrived.",ar:"لسه واصل حالًا.",note:"وصول"},
{id:89,en:"See you tomorrow.",ar:"أشوفك بكرة.",note:"وداع"},
{id:90,en:"Take care of yourself.",ar:"خلي بالك من نفسك.",note:"اهتمام"},

{id:91,en:"Good luck.",ar:"بالتوفيق.",note:"تشجيع"},
{id:92,en:"Congratulations!",ar:"مبروك!",note:"تهنئة"},
{id:93,en:"Happy birthday!",ar:"عيد ميلاد سعيد!",note:"مناسبة"},
{id:94,en:"Enjoy your day.",ar:"استمتع بيومك.",note:"إيجابية"},
{id:95,en:"Have a safe trip.",ar:"رحلة سعيدة.",note:"سفر"},
{id:96,en:"Drive safely.",ar:"اسوق بالراحة.",note:"تحذير"},
{id:97,en:"See you soon.",ar:"أشوفك قريب.",note:"وداع"},
{id:98,en:"Text me when you arrive.",ar:"ابعتلي لما توصل.",note:"متابعة"},
{id:99,en:"I appreciate your help.",ar:"مقدر مساعدتك.",note:"شكر"},
{id:100,en:"Everything will be fine.",ar:"كل حاجة هتبقى تمام.",note:"طمأنة"},
{id:101,en:"I'm not ready yet.",ar:"أنا مش جاهز لسه.",note:"تأجيل"},
{id:102,en:"Give me another chance.",ar:"اديني فرصة تانية.",note:"طلب"},
{id:103,en:"I totally forgot.",ar:"أنا نسيت خالص.",note:"نسيان"},
{id:104,en:"That makes sense.",ar:"ده منطقي.",note:"اتفاق"},
{id:105,en:"I changed my mind.",ar:"غيرت رأيي.",note:"قرار"},
{id:106,en:"It's up to you.",ar:"القرار يرجعلك.",note:"اختيار"},
{id:107,en:"I don't feel well.",ar:"أنا مش حاسس إني كويس.",note:"صحة"},
{id:108,en:"I need some fresh air.",ar:"محتاج شوية هوا.",note:"راحة"},
{id:109,en:"Can you hear me?",ar:"إنت سامعني؟",note:"اتصال"},
{id:110,en:"The connection is bad.",ar:"الاتصال وحش.",note:"مكالمة"},

{id:111,en:"I can't hear you clearly.",ar:"مش سامعك كويس.",note:"مكالمة"},
{id:112,en:"Your voice is breaking up.",ar:"صوتك بيقطع.",note:"مكالمة"},
{id:113,en:"Hold on a second.",ar:"استنى ثانية.",note:"انتظار"},
{id:114,en:"I'm almost done.",ar:"أنا قربت أخلص.",note:"وقت"},
{id:115,en:"Let's do it together.",ar:"نعملها سوا.",note:"تعاون"},
{id:116,en:"I need more time.",ar:"محتاج وقت أكتر.",note:"وقت"},
{id:117,en:"This is difficult.",ar:"ده صعب.",note:"وصف"},
{id:118,en:"This is easy.",ar:"ده سهل.",note:"وصف"},
{id:119,en:"I can handle it.",ar:"أقدر أتعامل معاه.",note:"ثقة"},
{id:120,en:"Everything is under control.",ar:"كل حاجة تحت السيطرة.",note:"طمأنة"},

{id:121,en:"I feel nervous.",ar:"حاسس بتوتر.",note:"مشاعر"},
{id:122,en:"Take a deep breath.",ar:"خد نفس عميق.",note:"تهدئة"},
{id:123,en:"You can do it.",ar:"إنت تقدر تعملها.",note:"تشجيع"},
{id:124,en:"Believe in yourself.",ar:"ثق في نفسك.",note:"تحفيز"},
{id:125,en:"Don't give up.",ar:"ما تستسلمش.",note:"تحفيز"},
{id:126,en:"Keep going.",ar:"كمل.",note:"تشجيع"},
{id:127,en:"I trust your opinion.",ar:"أنا بثق في رأيك.",note:"ثقة"},
{id:128,en:"What do you recommend?",ar:"إيه اللي تنصح بيه؟",note:"طلب رأي"},
{id:129,en:"I will think about it.",ar:"هفكر في الموضوع.",note:"تفكير"},
{id:130,en:"That sounds great.",ar:"ده شكله ممتاز.",note:"إعجاب"},

{id:131,en:"I'm not sure.",ar:"أنا مش متأكد.",note:"تردد"},
{id:132,en:"Maybe later.",ar:"يمكن بعدين.",note:"تأجيل"},
{id:133,en:"Let's see what happens.",ar:"نشوف هيحصل إيه.",note:"ترقب"},
{id:134,en:"I wasn't expecting that.",ar:"ماكنتش متوقع ده.",note:"مفاجأة"},
{id:135,en:"That's interesting.",ar:"ده مثير للاهتمام.",note:"اهتمام"},
{id:136,en:"That's unbelievable.",ar:"ده مش معقول.",note:"تعجب"},
{id:137,en:"What a surprise!",ar:"يا للمفاجأة!",note:"مفاجأة"},
{id:138,en:"You scared me.",ar:"خضتني.",note:"موقف"},
{id:139,en:"It's not a big deal.",ar:"مش مشكلة كبيرة.",note:"تهوين"},
{id:140,en:"Forget about it.",ar:"انسى الموضوع.",note:"تجاوز"},

{id:141,en:"I appreciate your honesty.",ar:"أقدر صراحتك.",note:"تقدير"},
{id:142,en:"Thanks for understanding.",ar:"شكرًا لتفهمك.",note:"شكر"},
{id:143,en:"I owe you one.",ar:"أنا مديونلك بواحدة.",note:"امتنان"},
{id:144,en:"No need to apologize.",ar:"مفيش داعي للاعتذار.",note:"تسامح"},
{id:145,en:"It wasn't your fault.",ar:"مش غلطتك.",note:"دعم"},
{id:146,en:"Everyone makes mistakes.",ar:"كل الناس بتغلط.",note:"طمأنة"},
{id:147,en:"Learn from your mistakes.",ar:"اتعلم من أخطائك.",note:"نصيحة"},
{id:148,en:"I need a break.",ar:"محتاج بريك.",note:"راحة"},
{id:149,en:"Let's take a walk.",ar:"يلا نتمشى.",note:"اقتراح"},
{id:150,en:"I need some silence.",ar:"محتاج شوية هدوء.",note:"راحة"},

{id:151,en:"Can you keep a secret?",ar:"ممكن تحتفظ بسر؟",note:"سر"},
{id:152,en:"Don't tell anyone.",ar:"ما تقولش لحد.",note:"سر"},
{id:153,en:"I promise.",ar:"أوعدك.",note:"وعد"},
{id:154,en:"Trust me.",ar:"ثق فيا.",note:"ثقة"},
{id:155,en:"I'm telling the truth.",ar:"أنا بقول الحقيقة.",note:"تأكيد"},
{id:156,en:"Why are you laughing?",ar:"إنت بتضحك ليه؟",note:"سؤال"},
{id:157,en:"I'm just joking.",ar:"أنا بهزر بس.",note:"مزاح"},
{id:158,en:"Seriously?",ar:"بجد؟",note:"تعجب"},
{id:159,en:"You must be kidding.",ar:"أكيد بتهزر.",note:"عدم تصديق"},
{id:160,en:"That's hilarious.",ar:"دي مضحكة جدًا.",note:"ضحك"},

{id:161,en:"I feel embarrassed.",ar:"حاسس بإحراج.",note:"مشاعر"},
{id:162,en:"It happens sometimes.",ar:"بتحصل أحيانًا.",note:"طمأنة"},
{id:163,en:"Don't blame yourself.",ar:"ما تلومش نفسك.",note:"دعم"},
{id:164,en:"I'm proud of you.",ar:"أنا فخور بيك.",note:"تشجيع"},
{id:165,en:"You did a great job.",ar:"إنت عملت شغل ممتاز.",note:"مدح"},
{id:166,en:"I respect you.",ar:"أنا بحترمك.",note:"احترام"},
{id:167,en:"That was very kind.",ar:"ده كان لطف منك.",note:"امتنان"},
{id:168,en:"Can I trust you?",ar:"أقدر أثق فيك؟",note:"ثقة"},
{id:169,en:"Please be honest with me.",ar:"خليك صريح معايا.",note:"صراحة"},
{id:170,en:"I understand your situation.",ar:"أنا فاهم موقفك.",note:"تفهم"},

{id:171,en:"Let's stay positive.",ar:"خلينا إيجابيين.",note:"تحفيز"},
{id:172,en:"Things will improve.",ar:"الأمور هتتحسن.",note:"تفاؤل"},
{id:173,en:"I'm trying my best.",ar:"أنا بحاول بأقصى جهدي.",note:"مجهود"},
{id:174,en:"That's enough for today.",ar:"كفاية النهارده.",note:"توقف"},
{id:175,en:"Tomorrow is another day.",ar:"بكرة يوم جديد.",note:"تفاؤل"},
{id:176,en:"I need to focus.",ar:"محتاج أركز.",note:"تركيز"},
{id:177,en:"Don't distract me.",ar:"ما تشتتنيش.",note:"تركيز"},
{id:178,en:"I can't concentrate.",ar:"مش قادر أركز.",note:"تركيز"},
{id:179,en:"Let's fix this problem.",ar:"يلا نحل المشكلة دي.",note:"حل مشاكل"},
{id:180,en:"We need a solution.",ar:"إحنا محتاجين حل.",note:"حل مشاكل"},

{id:181,en:"This is urgent.",ar:"ده ضروري جدًا.",note:"استعجال"},
{id:182,en:"Call me immediately.",ar:"كلمني فورًا.",note:"استعجال"},
{id:183,en:"I will be there soon.",ar:"هكون هناك قريب.",note:"وصول"},
{id:184,en:"I'm running late.",ar:"أنا متأخر.",note:"وقت"},
{id:185,en:"Traffic is terrible.",ar:"الزحمة فظيعة.",note:"مواصلات"},
{id:186,en:"The place is crowded.",ar:"المكان زحمة.",note:"مكان"},
{id:187,en:"I can't find parking.",ar:"مش لاقي ركنة.",note:"سيارة"},
{id:188,en:"Let's meet outside.",ar:"نتقابل بره.",note:"مقابلة"},
{id:189,en:"I'm waiting for you.",ar:"أنا مستنيك.",note:"انتظار"},
{id:190,en:"Where have you been?",ar:"إنت كنت فين؟",note:"سؤال"},

{id:191,en:"I had a long day.",ar:"كان يوم طويل.",note:"تعب"},
{id:192,en:"I need some sleep.",ar:"محتاج أنام شوية.",note:"راحة"},
{id:193,en:"I'm exhausted.",ar:"أنا مرهق جدًا.",note:"تعب"},
{id:194,en:"Let's relax.",ar:"يلا نسترخي.",note:"راحة"},
{id:195,en:"Turn off the lights.",ar:"اطفي النور.",note:"منزل"},
{id:196,en:"Close the door, please.",ar:"اقفل الباب لو سمحت.",note:"منزل"},
{id:197,en:"Open the window.",ar:"افتح الشباك.",note:"منزل"},
{id:198,en:"It's too hot here.",ar:"الجو حر هنا.",note:"طقس"},
{id:199,en:"It's really cold today.",ar:"الدنيا برد النهارده.",note:"طقس"},
{id:200,en:"I hope everything goes well.",ar:"أتمنى كل حاجة تمشي كويس.",note:"أمل"},
{id:201,en:"I woke up late today.",ar:"صحيت متأخر النهارده.",note:"روتين يومي"},
{id:202,en:"I missed the bus.",ar:"فاتني الأوتوبيس.",note:"مواصلات"},
{id:203,en:"I need to hurry.",ar:"لازم أستعجل.",note:"وقت"},
{id:204,en:"I'm stuck in traffic.",ar:"أنا واقف في الزحمة.",note:"مواصلات"},
{id:205,en:"The road is blocked.",ar:"الطريق مقفول.",note:"مواصلات"},
{id:206,en:"Can you pick me up?",ar:"ممكن تيجي تاخدني؟",note:"طلب"},
{id:207,en:"I'll send you my location.",ar:"هبعتلك اللوكيشن.",note:"موقع"},
{id:208,en:"My phone is about to die.",ar:"موبايلي قرب يفصل.",note:"هاتف"},
{id:209,en:"I forgot my password.",ar:"نسيت الباسورد.",note:"تكنولوجيا"},
{id:210,en:"The app keeps crashing.",ar:"التطبيق بيفصل باستمرار.",note:"تكنولوجيا"},

{id:211,en:"I need to recharge my phone.",ar:"محتاج أشحن موبايلي.",note:"هاتف"},
{id:212,en:"The signal is weak.",ar:"الإشارة ضعيفة.",note:"اتصال"},
{id:213,en:"I can't connect to the internet.",ar:"مش عارف أوصل للإنترنت.",note:"إنترنت"},
{id:214,en:"Try restarting it.",ar:"جرّب تعيد تشغيله.",note:"حل مشكلة"},
{id:215,en:"It's finally working now.",ar:"اشتغل أخيرًا دلوقتي.",note:"حل مشكلة"},
{id:216,en:"I need a favor.",ar:"محتاج خدمة.",note:"طلب"},
{id:217,en:"Can you do me a favor?",ar:"ممكن تعملي خدمة؟",note:"طلب"},
{id:218,en:"Sure, no problem.",ar:"أكيد، مفيش مشكلة.",note:"موافقة"},
{id:219,en:"I really appreciate it.",ar:"أنا مقدر ده جدًا.",note:"امتنان"},
{id:220,en:"You saved me.",ar:"إنت أنقذتني.",note:"شكر"},

{id:221,en:"I didn't expect this.",ar:"ماكنتش متوقع ده.",note:"مفاجأة"},
{id:222,en:"That's unbelievable.",ar:"ده لا يصدق.",note:"تعجب"},
{id:223,en:"I can't believe it.",ar:"مش مصدق.",note:"تعجب"},
{id:224,en:"What a coincidence!",ar:"يا للصدفة!",note:"موقف"},
{id:225,en:"This is getting weird.",ar:"الموضوع بقى غريب.",note:"تعجب"},
{id:226,en:"Something feels wrong.",ar:"حاسس إن في حاجة غلط.",note:"إحساس"},
{id:227,en:"I have a bad feeling.",ar:"عندي إحساس وحش.",note:"مشاعر"},
{id:228,en:"Don't overthink it.",ar:"ما تفكرش زيادة.",note:"نصيحة"},
{id:229,en:"Just relax.",ar:"بس اهدى.",note:"تهدئة"},
{id:230,en:"Everything happens for a reason.",ar:"كل حاجة بتحصل لسبب.",note:"فلسفة"},

{id:231,en:"Let's change the subject.",ar:"خلينا نغير الموضوع.",note:"محادثة"},
{id:232,en:"That's none of my business.",ar:"دي مش مشكلتي.",note:"تدخل"},
{id:233,en:"Mind your own business.",ar:"خليك في حالك.",note:"حدود"},
{id:234,en:"I didn't mean that.",ar:"ماكنتش أقصد كده.",note:"توضيح"},
{id:235,en:"You misunderstood me.",ar:"إنت فهمتني غلط.",note:"توضيح"},
{id:236,en:"Let me explain.",ar:"خليني أوضح.",note:"شرح"},
{id:237,en:"Now I understand.",ar:"دلوقتي فهمت.",note:"فهم"},
{id:238,en:"That makes more sense.",ar:"كده منطقي أكتر.",note:"فهم"},
{id:239,en:"You're absolutely right.",ar:"إنت معاك حق تمامًا.",note:"اتفاق"},
{id:240,en:"I completely disagree.",ar:"أنا مختلف تمامًا.",note:"اختلاف"},

{id:241,en:"Let's not argue.",ar:"بلاش نتخانق.",note:"تهدئة"},
{id:242,en:"Calm down and listen.",ar:"اهدى واسمع.",note:"تهدئة"},
{id:243,en:"I didn't say that.",ar:"أنا ماقولتش كده.",note:"دفاع"},
{id:244,en:"You're taking it personally.",ar:"إنت واخد الموضوع بشكل شخصي.",note:"نقاش"},
{id:245,en:"Forget what I said.",ar:"انسَ اللي قولته.",note:"تراجع"},
{id:246,en:"I need some space.",ar:"محتاج شوية مساحة.",note:"مشاعر"},
{id:247,en:"Leave me alone for a while.",ar:"سيبني لوحدي شوية.",note:"خصوصية"},
{id:248,en:"I'm trying to stay calm.",ar:"بحاول أهدى.",note:"مشاعر"},
{id:249,en:"This situation is stressful.",ar:"الموقف ده متعب.",note:"ضغط"},
{id:250,en:"I'm mentally exhausted.",ar:"أنا مرهق نفسيًا.",note:"تعب"},

{id:251,en:"Let's grab some coffee.",ar:"يلا نجيب قهوة.",note:"خروجة"},
{id:252,en:"I'm craving something sweet.",ar:"نفسي في حاجة حلوة.",note:"طعام"},
{id:253,en:"Let's order food.",ar:"يلا نطلب أكل.",note:"طعام"},
{id:254,en:"What do you want to eat?",ar:"عايز تاكل إيه؟",note:"طعام"},
{id:255,en:"I'm not hungry anymore.",ar:"أنا مش جعان دلوقتي.",note:"طعام"},
{id:256,en:"This tastes amazing.",ar:"طعمه رهيب.",note:"طعام"},
{id:257,en:"It's too salty.",ar:"مالح زيادة.",note:"طعام"},
{id:258,en:"It's too spicy.",ar:"حرّاق زيادة.",note:"طعام"},
{id:259,en:"Can I get some water?",ar:"ممكن شوية مية؟",note:"طلب"},
{id:260,en:"I'm full.",ar:"أنا شبعت.",note:"طعام"},

{id:261,en:"I need to save money.",ar:"لازم أوفر فلوس.",note:"مال"},
{id:262,en:"I'm broke right now.",ar:"أنا مفلس دلوقتي.",note:"مال"},
{id:263,en:"Can you lend me some money?",ar:"ممكن تسلفني شوية فلوس؟",note:"مال"},
{id:264,en:"I'll pay you back later.",ar:"هرجعهالك بعدين.",note:"مال"},
{id:265,en:"I spent too much today.",ar:"صرفت كتير النهارده.",note:"مال"},
{id:266,en:"This is worth it.",ar:"ده يستاهل.",note:"شراء"},
{id:267,en:"I found a cheaper option.",ar:"لقيت خيار أرخص.",note:"شراء"},
{id:268,en:"Let's split the bill.",ar:"نقسم الحساب.",note:"دفع"},
{id:269,en:"I forgot my wallet at home.",ar:"نسيت المحفظة في البيت.",note:"نسيان"},
{id:270,en:"Can you cover me this time?",ar:"ممكن تحاسب المرة دي؟",note:"مال"},

{id:271,en:"I need motivation.",ar:"محتاج تحفيز.",note:"تحفيز"},
{id:272,en:"I'm losing focus.",ar:"بدأت أفقد تركيزي.",note:"تركيز"},
{id:273,en:"Stay focused on your goals.",ar:"ركز على أهدافك.",note:"تحفيز"},
{id:274,en:"Hard work pays off.",ar:"التعب بيجيب نتيجة.",note:"تحفيز"},
{id:275,en:"Success takes patience.",ar:"النجاح يحتاج صبر.",note:"تحفيز"},
{id:276,en:"Don't compare yourself to others.",ar:"ما تقارنش نفسك بحد.",note:"تطوير"},
{id:277,en:"Everyone has their own journey.",ar:"كل واحد له رحلته.",note:"تطوير"},
{id:278,en:"Believe in the process.",ar:"ثق في الرحلة.",note:"تحفيز"},
{id:279,en:"Small progress is still progress.",ar:"التقدم البسيط يعتبر تقدم.",note:"تحفيز"},
{id:280,en:"Keep improving yourself.",ar:"استمر في تطوير نفسك.",note:"تطوير"},

{id:281,en:"I need to organize my time.",ar:"محتاج أنظم وقتي.",note:"تنظيم"},
{id:282,en:"I'm always distracted.",ar:"أنا دايمًا مشتت.",note:"تركيز"},
{id:283,en:"I have too much to do.",ar:"عندي حاجات كتير أعملها.",note:"ضغط"},
{id:284,en:"One step at a time.",ar:"خطوة خطوة.",note:"تحفيز"},
{id:285,en:"Let's make a plan.",ar:"يلا نحط خطة.",note:"تنظيم"},
{id:286,en:"Write it down.",ar:"اكتبها.",note:"تنظيم"},
{id:287,en:"Don't forget the details.",ar:"ما تنساش التفاصيل.",note:"تنظيم"},
{id:288,en:"Double-check everything.",ar:"راجع كل حاجة مرتين.",note:"تنظيم"},
{id:289,en:"Preparation is important.",ar:"التحضير مهم.",note:"تطوير"},
{id:290,en:"Timing is everything.",ar:"التوقيت مهم جدًا.",note:"وقت"},

{id:291,en:"I need some inspiration.",ar:"محتاج إلهام.",note:"تحفيز"},
{id:292,en:"This motivates me.",ar:"ده بيحفزني.",note:"تحفيز"},
{id:293,en:"I learned something new today.",ar:"اتعلمت حاجة جديدة النهارده.",note:"تعلم"},
{id:294,en:"Knowledge is power.",ar:"المعرفة قوة.",note:"تعلم"},
{id:295,en:"Experience teaches everything.",ar:"الخبرة بتعلم كل حاجة.",note:"خبرة"},
{id:296,en:"Mistakes help us grow.",ar:"الأخطاء بتساعدنا نتطور.",note:"تعلم"},
{id:297,en:"I won't repeat that mistake.",ar:"مش هكرر الغلطة دي.",note:"تعلم"},
{id:298,en:"Life is teaching me lessons.",ar:"الحياة بتعلمني دروس.",note:"حياة"},
{id:299,en:"Every day is a new chance.",ar:"كل يوم فرصة جديدة.",note:"تفاؤل"},
{id:300,en:"I'm ready for the next step.",ar:"أنا جاهز للخطوة الجاية.",note:"تطوير"},
{id:301,en:"I need to clear my mind.",ar:"محتاج أصفّي دماغي.",note:"راحة"},
{id:302,en:"Let's start over.",ar:"نبدأ من جديد.",note:"بداية"},
{id:303,en:"Today feels different.",ar:"النهارده مختلف.",note:"إحساس"},
{id:304,en:"I have mixed feelings.",ar:"عندي مشاعر متلخبطة.",note:"مشاعر"},
{id:305,en:"I feel more confident now.",ar:"حاسس بثقة أكتر دلوقتي.",note:"ثقة"},
{id:306,en:"I'm trying to stay positive.",ar:"بحاول أبقى إيجابي.",note:"إيجابية"},
{id:307,en:"This is not easy for me.",ar:"ده مش سهل بالنسبالي.",note:"صعوبة"},
{id:308,en:"I need to think carefully.",ar:"لازم أفكر كويس.",note:"تفكير"},
{id:309,en:"Let's not rush things.",ar:"بلاش نستعجل الأمور.",note:"هدوء"},
{id:310,en:"Take it step by step.",ar:"خدها خطوة خطوة.",note:"نصيحة"},

{id:311,en:"I need a fresh start.",ar:"محتاج بداية جديدة.",note:"بداية"},
{id:312,en:"I learned my lesson.",ar:"اتعلمت الدرس.",note:"تعلم"},
{id:313,en:"That changed my perspective.",ar:"ده غيّر طريقة تفكيري.",note:"تطوير"},
{id:314,en:"I need to improve myself.",ar:"لازم أطور نفسي.",note:"تطوير"},
{id:315,en:"I'm doing my best.",ar:"أنا بعمل اللي عليا.",note:"مجهود"},
{id:316,en:"I deserve better.",ar:"أنا أستحق الأفضل.",note:"ثقة"},
{id:317,en:"This is my decision.",ar:"ده قراري.",note:"قرار"},
{id:318,en:"I won't change my mind.",ar:"مش هغيّر رأيي.",note:"قرار"},
{id:319,en:"Let's move forward.",ar:"خلينا نكمل لقدام.",note:"تقدم"},
{id:320,en:"We need to be realistic.",ar:"لازم نكون واقعيين.",note:"تفكير"},

{id:321,en:"I don't feel comfortable.",ar:"أنا مش مرتاح.",note:"مشاعر"},
{id:322,en:"Something feels strange.",ar:"حاسس إن في حاجة غريبة.",note:"إحساس"},
{id:323,en:"I'm trying to understand.",ar:"بحاول أفهم.",note:"تفكير"},
{id:324,en:"I need more information.",ar:"محتاج معلومات أكتر.",note:"استفسار"},
{id:325,en:"Can you explain it differently?",ar:"ممكن تشرحها بطريقة تانية؟",note:"طلب توضيح"},
{id:326,en:"That helped a lot.",ar:"ده ساعد جدًا.",note:"امتنان"},
{id:327,en:"Now it's clear.",ar:"دلوقتي الموضوع واضح.",note:"فهم"},
{id:328,en:"I was confused before.",ar:"كنت متلخبط قبل كده.",note:"فهم"},
{id:329,en:"Everything makes sense now.",ar:"كل حاجة بقت منطقية دلوقتي.",note:"فهم"},
{id:330,en:"Thanks for your patience.",ar:"شكرًا على صبرك.",note:"شكر"},

{id:331,en:"I'm glad you came.",ar:"مبسوط إنك جيت.",note:"ترحيب"},
{id:332,en:"It's good to see you again.",ar:"حلو إني أشوفك تاني.",note:"لقاء"},
{id:333,en:"You look great today.",ar:"شكلك حلو النهارده.",note:"مجاملة"},
{id:334,en:"You seem tired.",ar:"شكلك تعبان.",note:"ملاحظة"},
{id:335,en:"Did something happen?",ar:"حصل حاجة؟",note:"اهتمام"},
{id:336,en:"I'm here if you need me.",ar:"أنا موجود لو احتجتني.",note:"دعم"},
{id:337,en:"You can talk to me anytime.",ar:"تقدر تكلمني في أي وقت.",note:"دعم"},
{id:338,en:"I understand how you feel.",ar:"أنا فاهم إنت حاسس بإيه.",note:"تفهم"},
{id:339,en:"Things will get better soon.",ar:"الأمور هتتحسن قريب.",note:"طمأنة"},
{id:340,en:"Don't lose hope.",ar:"ما تفقدش الأمل.",note:"تشجيع"},

{id:341,en:"I need some quiet time.",ar:"محتاج شوية هدوء.",note:"راحة"},
{id:342,en:"I just want to relax.",ar:"عايز أرتاح بس.",note:"راحة"},
{id:343,en:"Let's stay home today.",ar:"خلينا في البيت النهارده.",note:"اقتراح"},
{id:344,en:"I don't feel like going out.",ar:"مش حابب أخرج.",note:"مزاج"},
{id:345,en:"Maybe another time.",ar:"يمكن وقت تاني.",note:"تأجيل"},
{id:346,en:"I'm not in the mood.",ar:"مالييش مزاج.",note:"مشاعر"},
{id:347,en:"I need some alone time.",ar:"محتاج أقعد لوحدي شوية.",note:"خصوصية"},
{id:348,en:"I'm overthinking everything.",ar:"بفكر زيادة في كل حاجة.",note:"تفكير"},
{id:349,en:"My mind is exhausted.",ar:"دماغي مرهقة.",note:"تعب"},
{id:350,en:"I need a mental break.",ar:"محتاج بريك نفسي.",note:"راحة"},

{id:351,en:"Let's focus on solutions.",ar:"خلينا نركز على الحلول.",note:"حل مشاكل"},
{id:352,en:"Complaining won't help.",ar:"الشكوى مش هتفيد.",note:"نصيحة"},
{id:353,en:"We can solve this together.",ar:"نقدر نحل ده سوا.",note:"تعاون"},
{id:354,en:"There must be another way.",ar:"أكيد في طريقة تانية.",note:"حلول"},
{id:355,en:"Let's stay calm and think.",ar:"خلينا هاديين ونفكر.",note:"هدوء"},
{id:356,en:"I believe we can fix this.",ar:"مؤمن إننا نقدر نحل ده.",note:"ثقة"},
{id:357,en:"Nothing is impossible.",ar:"مفيش حاجة مستحيلة.",note:"تحفيز"},
{id:358,en:"We came too far to quit.",ar:"وصلنا بعيد أوي علشان نستسلم.",note:"تحفيز"},
{id:359,en:"Success needs consistency.",ar:"النجاح يحتاج استمرارية.",note:"تحفيز"},
{id:360,en:"Discipline is more important than motivation.",ar:"الالتزام أهم من الحماس.",note:"تطوير"},

{id:361,en:"I'm proud of my progress.",ar:"أنا فخور بتقدمي.",note:"إنجاز"},
{id:362,en:"I still have a lot to learn.",ar:"لسه عندي كتير أتعلمه.",note:"تعلم"},
{id:363,en:"Practice makes improvement.",ar:"الممارسة بتعمل تطور.",note:"تعلم"},
{id:364,en:"I'm getting better every day.",ar:"أنا بتحسن كل يوم.",note:"تطوير"},
{id:365,en:"I won't stop learning.",ar:"مش هبطل أتعلم.",note:"تعلم"},
{id:366,en:"This experience changed me.",ar:"التجربة دي غيّرتني.",note:"خبرة"},
{id:367,en:"Life teaches hard lessons.",ar:"الحياة بتعلم دروس صعبة.",note:"حياة"},
{id:368,en:"Pain can make you stronger.",ar:"الألم ممكن يقويك.",note:"تطوير"},
{id:369,en:"Everything happens at the right time.",ar:"كل حاجة بتحصل في وقتها الصح.",note:"تفاؤل"},
{id:370,en:"Good things take time.",ar:"الحاجات الحلوة بتاخد وقت.",note:"صبر"},

{id:371,en:"I need to recharge my energy.",ar:"محتاج أجدد طاقتي.",note:"طاقة"},
{id:372,en:"Today was productive.",ar:"النهارده كان مثمر.",note:"عمل"},
{id:373,en:"I wasted too much time.",ar:"ضيعت وقت كتير.",note:"وقت"},
{id:374,en:"I should sleep earlier.",ar:"لازم أنام بدري.",note:"روتين"},
{id:375,en:"Tomorrow will be busy.",ar:"بكرة هيبقى زحمة.",note:"وقت"},
{id:376,en:"I need a better routine.",ar:"محتاج روتين أفضل.",note:"تنظيم"},
{id:377,en:"I'm trying to stay organized.",ar:"بحاول أبقى منظم.",note:"تنظيم"},
{id:378,en:"I forgot what I wanted to say.",ar:"نسيت كنت عايز أقول إيه.",note:"نسيان"},
{id:379,en:"That reminds me of something.",ar:"ده فكرني بحاجة.",note:"تذكر"},
{id:380,en:"I remember now.",ar:"افتكرت دلوقتي.",note:"تذكر"},

{id:381,en:"Let's keep this between us.",ar:"خلّي الموضوع بينا.",note:"خصوصية"},
{id:382,en:"I trust your judgment.",ar:"أنا بثق في حكمك.",note:"ثقة"},
{id:383,en:"Be honest with yourself.",ar:"خليك صريح مع نفسك.",note:"نصيحة"},
{id:384,en:"You deserve to be happy.",ar:"إنت تستحق تكون سعيد.",note:"دعم"},
{id:385,en:"Don't be too hard on yourself.",ar:"ما تقساش على نفسك.",note:"دعم"},
{id:386,en:"Take care of your mental health.",ar:"اهتم بصحتك النفسية.",note:"صحة"},
{id:387,en:"Rest is important too.",ar:"الراحة مهمة برضه.",note:"راحة"},
{id:388,en:"Balance is everything.",ar:"التوازن هو كل حاجة.",note:"حياة"},
{id:389,en:"Enjoy the little moments.",ar:"استمتع باللحظات الصغيرة.",note:"حياة"},
{id:390,en:"Life goes by quickly.",ar:"الحياة بتمشي بسرعة.",note:"حياة"},

{id:391,en:"I need to make a decision soon.",ar:"لازم أقرر قريب.",note:"قرار"},
{id:392,en:"This opportunity won't last forever.",ar:"الفرصة دي مش هتفضل للأبد.",note:"فرص"},
{id:393,en:"Sometimes risks are necessary.",ar:"أحيانًا المخاطرة ضرورية.",note:"تطوير"},
{id:394,en:"I'm afraid of failing.",ar:"خايف أفشل.",note:"خوف"},
{id:395,en:"Failure is part of success.",ar:"الفشل جزء من النجاح.",note:"تحفيز"},
{id:396,en:"Every mistake teaches something.",ar:"كل غلطة بتعلم حاجة.",note:"تعلم"},
{id:397,en:"You learn more from experience.",ar:"بتتعلم أكتر من التجربة.",note:"خبرة"},
{id:398,en:"Confidence changes everything.",ar:"الثقة بتغير كل حاجة.",note:"ثقة"},
{id:399,en:"I finally understand myself better.",ar:"أخيرًا بقيت فاهم نفسي أكتر.",note:"تطوير"},
{id:400,en:"This is just the beginning.",ar:"دي مجرد البداية.",note:"بداية"},{id:401,en:"I need to reset my priorities.",ar:"محتاج أعيد ترتيب أولوياتي.",note:"تنظيم"},
{id:402,en:"I’ve been thinking a lot lately.",ar:"بفكر كتير الفترة دي.",note:"تفكير"},
{id:403,en:"My schedule is packed today.",ar:"جدولي زحمة النهارده.",note:"وقت"},
{id:404,en:"I barely had time to rest.",ar:"بالكاد لقيت وقت أرتاح.",note:"تعب"},
{id:405,en:"I need to slow down a little.",ar:"لازم أهدي شوية.",note:"راحة"},
{id:406,en:"Everything feels overwhelming.",ar:"حاسس إن كل حاجة فوق طاقتي.",note:"ضغط"},
{id:407,en:"I need to clear some things up.",ar:"محتاج أوضح شوية حاجات.",note:"توضيح"},
{id:408,en:"I don’t want any problems.",ar:"أنا مش عايز مشاكل.",note:"هدوء"},
{id:409,en:"Let’s keep things simple.",ar:"خلينا نبسط الأمور.",note:"هدوء"},
{id:410,en:"I just want peace of mind.",ar:"أنا عايز راحة بال بس.",note:"راحة"},

{id:411,en:"I didn't sleep well last night.",ar:"ما نمتش كويس امبارح.",note:"نوم"},
{id:412,en:"I kept thinking all night.",ar:"فضلت أفكر طول الليل.",note:"تفكير"},
{id:413,en:"I woke up feeling tired.",ar:"صحيت تعبان.",note:"تعب"},
{id:414,en:"Coffee helps me focus.",ar:"القهوة بتساعدني أركز.",note:"تركيز"},
{id:415,en:"I need more energy today.",ar:"محتاج طاقة أكتر النهارده.",note:"طاقة"},
{id:416,en:"I have too many responsibilities.",ar:"عندي مسؤوليات كتير.",note:"حياة"},
{id:417,en:"Life can be exhausting sometimes.",ar:"الحياة بتكون مرهقة أحيانًا.",note:"حياة"},
{id:418,en:"I need to manage my stress.",ar:"لازم أتحكم في توتري.",note:"ضغط"},
{id:419,en:"I'm trying not to overreact.",ar:"بحاول ما أبالغش في رد فعلي.",note:"مشاعر"},
{id:420,en:"Let's not make things worse.",ar:"بلاش نعقد الأمور أكتر.",note:"تهدئة"},

{id:421,en:"I appreciate your support.",ar:"أنا مقدر دعمك.",note:"امتنان"},
{id:422,en:"You always understand me.",ar:"إنت دايمًا فاهمني.",note:"علاقات"},
{id:423,en:"I needed to hear that.",ar:"كنت محتاج أسمع ده.",note:"دعم"},
{id:424,en:"That means a lot to me.",ar:"ده معناه كبير بالنسبالي.",note:"امتنان"},
{id:425,en:"You made my day.",ar:"إنت خليت يومي أحسن.",note:"امتنان"},
{id:426,en:"I’m grateful for everything.",ar:"أنا ممتن لكل حاجة.",note:"امتنان"},
{id:427,en:"I learned to be patient.",ar:"اتعلمت أكون صبور.",note:"تطوير"},
{id:428,en:"Patience changes everything.",ar:"الصبر بيغير كل حاجة.",note:"حكمة"},
{id:429,en:"I’m stronger than before.",ar:"أنا أقوى من قبل كده.",note:"ثقة"},
{id:430,en:"I survived difficult times.",ar:"عدّيت أوقات صعبة.",note:"تجارب"},

{id:431,en:"I’m trying to stay motivated.",ar:"بحاول أفضل متحفز.",note:"تحفيز"},
{id:432,en:"Some days are harder than others.",ar:"في أيام أصعب من غيرها.",note:"حياة"},
{id:433,en:"I need to stay disciplined.",ar:"لازم ألتزم.",note:"تطوير"},
{id:434,en:"Consistency is the key.",ar:"الاستمرارية هي المفتاح.",note:"نجاح"},
{id:435,en:"I’m building better habits.",ar:"ببني عادات أفضل.",note:"تطوير"},
{id:436,en:"I need to stop procrastinating.",ar:"لازم أبطل تأجيل.",note:"تنظيم"},
{id:437,en:"Time flies so fast.",ar:"الوقت بيجري بسرعة.",note:"وقت"},
{id:438,en:"I wish I started earlier.",ar:"كنت أتمنى أبدأ بدري.",note:"ندم"},
{id:439,en:"Better late than never.",ar:"متأخر أحسن من أبدًا.",note:"تحفيز"},
{id:440,en:"Today is a new opportunity.",ar:"النهارده فرصة جديدة.",note:"تفاؤل"},

{id:441,en:"I need to trust the process.",ar:"لازم أثق في الرحلة.",note:"تطوير"},
{id:442,en:"Growth takes time.",ar:"التطور بياخد وقت.",note:"صبر"},
{id:443,en:"I’m learning from every experience.",ar:"بتعلم من كل تجربة.",note:"تعلم"},
{id:444,en:"Every challenge teaches something.",ar:"كل تحدي بيعلم حاجة.",note:"تعلم"},
{id:445,en:"I’m becoming more mature.",ar:"بقيت أنضج أكتر.",note:"تطوير"},
{id:446,en:"Life changed me a lot.",ar:"الحياة غيرتني جدًا.",note:"تجارب"},
{id:447,en:"I see things differently now.",ar:"بشوف الأمور بشكل مختلف دلوقتي.",note:"تفكير"},
{id:448,en:"Experience changes your mindset.",ar:"الخبرة بتغير طريقة التفكير.",note:"خبرة"},
{id:449,en:"I know my worth now.",ar:"أنا عارف قيمتي دلوقتي.",note:"ثقة"},
{id:450,en:"I refuse to give up.",ar:"رافض أستسلم.",note:"إصرار"},

{id:451,en:"I need to stay focused.",ar:"لازم أفضل مركز.",note:"تركيز"},
{id:452,en:"Distractions waste time.",ar:"المشتتات بتضيع الوقت.",note:"تركيز"},
{id:453,en:"I’m trying to improve daily.",ar:"بحاول أتحسن يوميًا.",note:"تطوير"},
{id:454,en:"Small changes make a difference.",ar:"التغييرات الصغيرة بتفرق.",note:"تطوير"},
{id:455,en:"I’m working on myself.",ar:"بشتغل على نفسي.",note:"تطوير"},
{id:456,en:"I’m not the same person anymore.",ar:"أنا مش نفس الشخص خلاص.",note:"تغيير"},
{id:457,en:"I learned to value my peace.",ar:"اتعلمت أقدّر راحة بالي.",note:"راحة"},
{id:458,en:"Protect your energy.",ar:"احمي طاقتك.",note:"طاقة"},
{id:459,en:"Not everyone deserves your time.",ar:"مش كل الناس تستحق وقتك.",note:"علاقات"},
{id:460,en:"Choose your circle wisely.",ar:"اختار دايرتك بعناية.",note:"علاقات"},

{id:461,en:"I need to stay away from negativity.",ar:"لازم أبعد عن السلبية.",note:"طاقة"},
{id:462,en:"Positive people inspire me.",ar:"الناس الإيجابية بتلهمني.",note:"إيجابية"},
{id:463,en:"I enjoy meaningful conversations.",ar:"بحب الكلام اللي له معنى.",note:"محادثات"},
{id:464,en:"Silence can be powerful.",ar:"السكوت أحيانًا بيكون قوي.",note:"حكمة"},
{id:465,en:"Actions speak louder than words.",ar:"الأفعال أقوى من الكلام.",note:"حكمة"},
{id:466,en:"I need honesty in my life.",ar:"محتاج الصراحة في حياتي.",note:"علاقات"},
{id:467,en:"Trust is hard to rebuild.",ar:"الثقة صعب ترجع.",note:"ثقة"},
{id:468,en:"I hate fake behavior.",ar:"بكره التصنع.",note:"مشاعر"},
{id:469,en:"Be real with me.",ar:"خليك حقيقي معايا.",note:"صراحة"},
{id:470,en:"I respect genuine people.",ar:"بحترم الناس الحقيقية.",note:"احترام"},

{id:471,en:"I need to improve my communication.",ar:"لازم أحسن طريقة تواصلي.",note:"تطوير"},
{id:472,en:"Sometimes listening is enough.",ar:"أحيانًا السماع كفاية.",note:"تواصل"},
{id:473,en:"I don’t like misunderstandings.",ar:"ما بحبش سوء الفهم.",note:"تواصل"},
{id:474,en:"Clear communication matters.",ar:"التواصل الواضح مهم.",note:"تواصل"},
{id:475,en:"Words can hurt deeply.",ar:"الكلام ممكن يوجع جدًا.",note:"مشاعر"},
{id:476,en:"Think before you speak.",ar:"فكر قبل ما تتكلم.",note:"نصيحة"},
{id:477,en:"Kindness costs nothing.",ar:"الطيبة ما بتكلفش حاجة.",note:"حكمة"},
{id:478,en:"Respect should be mutual.",ar:"الاحترام لازم يكون متبادل.",note:"علاقات"},
{id:479,en:"I value loyalty.",ar:"بقدّر الوفاء.",note:"علاقات"},
{id:480,en:"Real friends are rare.",ar:"الأصدقاء الحقيقيين قليلين.",note:"علاقات"},

{id:481,en:"I need a fresh perspective.",ar:"محتاج نظرة جديدة.",note:"تفكير"},
{id:482,en:"Maybe everything happens for a reason.",ar:"يمكن كل حاجة بتحصل لسبب.",note:"حكمة"},
{id:483,en:"I believe better days are coming.",ar:"مؤمن إن الأيام الحلوة جاية.",note:"تفاؤل"},
{id:484,en:"Nothing stays the same forever.",ar:"مفيش حاجة بتفضل زي ما هي للأبد.",note:"حياة"},
{id:485,en:"Change is part of life.",ar:"التغيير جزء من الحياة.",note:"حياة"},
{id:486,en:"I’m learning to let go.",ar:"بتعلم أسيب الأمور تمشي.",note:"تطوير"},
{id:487,en:"Holding on hurts sometimes.",ar:"التمسك أحيانًا بيوجع.",note:"مشاعر"},
{id:488,en:"Peace is more important than winning.",ar:"راحة البال أهم من المكسب.",note:"حكمة"},
{id:489,en:"I choose peace over drama.",ar:"بختار السلام بدل الدراما.",note:"راحة"},
{id:490,en:"Life feels lighter now.",ar:"الحياة بقت أخف دلوقتي.",note:"مشاعر"},

{id:491,en:"I still have big dreams.",ar:"لسه عندي أحلام كبيرة.",note:"أحلام"},
{id:492,en:"I’m working toward my goals.",ar:"بشتغل على أهدافي.",note:"أهداف"},
{id:493,en:"Success doesn’t happen overnight.",ar:"النجاح ما بيحصلش في يوم وليلة.",note:"نجاح"},
{id:494,en:"Hard times build strong people.",ar:"الأوقات الصعبة بتبني ناس قوية.",note:"تحفيز"},
{id:495,en:"I want a better future.",ar:"عايز مستقبل أفضل.",note:"طموح"},
{id:496,en:"I’m not afraid to start again.",ar:"مش خايف أبدأ من جديد.",note:"بداية"},
{id:497,en:"I learned to believe in myself.",ar:"اتعلمت أصدق نفسي.",note:"ثقة"},
{id:498,en:"Confidence changes your life.",ar:"الثقة بتغير حياتك.",note:"ثقة"},
{id:499,en:"I’m becoming the best version of myself.",ar:"ببقى أفضل نسخة من نفسي.",note:"تطوير"},
{id:500,en:"This journey is worth it.",ar:"الرحلة دي تستحق.",note:"تحفيز"},
{id:501,en:"I need to get my life together.",ar:"لازم أرتب حياتي.",note:"تنظيم"},
{id:502,en:"I’ve been under a lot of pressure.",ar:"كنت تحت ضغط كبير.",note:"ضغط"},
{id:503,en:"I just need some peace and quiet.",ar:"أنا محتاج هدوء وراحة بس.",note:"راحة"},
{id:504,en:"I’m trying to stay strong.",ar:"بحاول أفضل قوي.",note:"قوة"},
{id:505,en:"Some things are out of my control.",ar:"في حاجات خارج سيطرتي.",note:"تقبل"},
{id:506,en:"I need to accept reality.",ar:"لازم أتقبل الواقع.",note:"تقبل"},
{id:507,en:"I’m learning to move on.",ar:"بتعلم أكمّل.",note:"تطوير"},
{id:508,en:"I can’t keep living in the past.",ar:"مش هفضل عايش في الماضي.",note:"حياة"},
{id:509,en:"Every day is a new lesson.",ar:"كل يوم درس جديد.",note:"تعلم"},
{id:510,en:"I need to focus on what matters.",ar:"لازم أركز على المهم.",note:"تركيز"},

{id:511,en:"I’m trying to avoid negativity.",ar:"بحاول أتجنب السلبية.",note:"طاقة"},
{id:512,en:"I need more positivity in my life.",ar:"محتاج إيجابية أكتر في حياتي.",note:"إيجابية"},
{id:513,en:"I’m protecting my peace now.",ar:"بقيت بحمي راحة بالي.",note:"راحة"},
{id:514,en:"I don't argue anymore.",ar:"ما بقيتش أحب الجدال.",note:"هدوء"},
{id:515,en:"Some battles aren't worth it.",ar:"في معارك ما تستاهلش.",note:"حكمة"},
{id:516,en:"I’d rather stay calm.",ar:"أفضل أبقى هادي.",note:"هدوء"},
{id:517,en:"I’m done explaining myself.",ar:"بطلت أبرر نفسي.",note:"ثقة"},
{id:518,en:"People show their true colors eventually.",ar:"الناس بتظهر حقيقتها في الآخر.",note:"حكمة"},
{id:519,en:"Experience changes how you see people.",ar:"الخبرة بتغير نظرتك للناس.",note:"خبرة"},
{id:520,en:"I trust actions more than words.",ar:"بثق في الأفعال أكتر من الكلام.",note:"ثقة"},

{id:521,en:"I need to stay disciplined.",ar:"لازم ألتزم.",note:"تطوير"},
{id:522,en:"Motivation comes and goes.",ar:"الحماس بييجي ويروح.",note:"تحفيز"},
{id:523,en:"Discipline keeps you going.",ar:"الالتزام هو اللي بيكمّل.",note:"نجاح"},
{id:524,en:"I’m trying to build consistency.",ar:"بحاول أبني استمرارية.",note:"تطوير"},
{id:525,en:"Success requires patience.",ar:"النجاح يحتاج صبر.",note:"نجاح"},
{id:526,en:"I need to trust myself more.",ar:"لازم أثق في نفسي أكتر.",note:"ثقة"},
{id:527,en:"I’m capable of more.",ar:"أنا أقدر على أكتر.",note:"ثقة"},
{id:528,en:"I know I can succeed.",ar:"أنا عارف إني أقدر أنجح.",note:"ثقة"},
{id:529,en:"I just need more experience.",ar:"أنا محتاج خبرة أكتر بس.",note:"خبرة"},
{id:530,en:"Practice improves everything.",ar:"الممارسة بتحسن كل حاجة.",note:"تعلم"},

{id:531,en:"I’m trying to manage my emotions.",ar:"بحاول أتحكم في مشاعري.",note:"مشاعر"},
{id:532,en:"I get stressed too easily.",ar:"بتوتر بسهولة.",note:"توتر"},
{id:533,en:"I need to stop overthinking.",ar:"لازم أبطل تفكير زيادة.",note:"تفكير"},
{id:534,en:"My thoughts keep racing.",ar:"أفكاري مش بتقف.",note:"تفكير"},
{id:535,en:"I need to calm my mind.",ar:"لازم أهدي دماغي.",note:"راحة"},
{id:536,en:"Meditation helps sometimes.",ar:"التأمل بيساعد أحيانًا.",note:"راحة"},
{id:537,en:"Music relaxes me.",ar:"المزيكا بترتاحني.",note:"راحة"},
{id:538,en:"I need a break from everything.",ar:"محتاج بريك من كل حاجة.",note:"راحة"},
{id:539,en:"I’m mentally drained.",ar:"مستنزف نفسيًا.",note:"تعب"},
{id:540,en:"I need to recharge.",ar:"محتاج أستعيد طاقتي.",note:"طاقة"},

{id:541,en:"I’m trying to be more organized.",ar:"بحاول أبقى منظم أكتر.",note:"تنظيم"},
{id:542,en:"My room is a mess.",ar:"أوضتي مكركبة.",note:"منزل"},
{id:543,en:"I need to clean up.",ar:"لازم أرتب.",note:"تنظيم"},
{id:544,en:"I forgot where I put it.",ar:"نسيت أنا حطيته فين.",note:"نسيان"},
{id:545,en:"I lose things all the time.",ar:"بضيع حاجات طول الوقت.",note:"نسيان"},
{id:546,en:"I need to be more careful.",ar:"لازم أخد بالي أكتر.",note:"حذر"},
{id:547,en:"I’m always in a rush.",ar:"أنا دايمًا مستعجل.",note:"وقت"},
{id:548,en:"I need to slow down.",ar:"لازم أهدي.",note:"راحة"},
{id:549,en:"I barely have free time.",ar:"بالكاد عندي وقت فاضي.",note:"وقت"},
{id:550,en:"I need a vacation.",ar:"محتاج أجازة.",note:"راحة"},

{id:551,en:"I miss the old days.",ar:"وحشتني الأيام القديمة.",note:"ذكريات"},
{id:552,en:"Life was simpler back then.",ar:"الحياة كانت أبسط زمان.",note:"ذكريات"},
{id:553,en:"People change over time.",ar:"الناس بتتغير مع الوقت.",note:"حياة"},
{id:554,en:"Nothing lasts forever.",ar:"مفيش حاجة بتدوم للأبد.",note:"حكمة"},
{id:555,en:"Time changes everything.",ar:"الوقت بيغير كل حاجة.",note:"حكمة"},
{id:556,en:"I learned to appreciate small things.",ar:"اتعلمت أقدّر الحاجات الصغيرة.",note:"تطوير"},
{id:557,en:"Happiness comes from within.",ar:"السعادة بتيجي من جواك.",note:"حكمة"},
{id:558,en:"Peace is priceless.",ar:"راحة البال مالهاش تمن.",note:"راحة"},
{id:559,en:"I want a peaceful life.",ar:"عايز حياة هادية.",note:"حياة"},
{id:560,en:"I’m tired of unnecessary drama.",ar:"زهقت من الدراما الفاضية.",note:"علاقات"},

{id:561,en:"I value honesty more now.",ar:"بقيت أقدّر الصراحة أكتر.",note:"علاقات"},
{id:562,en:"Trust takes years to build.",ar:"الثقة بتاخد سنين علشان تتبني.",note:"ثقة"},
{id:563,en:"One lie can ruin everything.",ar:"كدبة واحدة ممكن تبوظ كل حاجة.",note:"ثقة"},
{id:564,en:"I prefer real conversations.",ar:"أفضل الكلام الحقيقي.",note:"محادثات"},
{id:565,en:"I hate fake compliments.",ar:"بكره المجاملات المزيفة.",note:"مشاعر"},
{id:566,en:"I appreciate genuine people.",ar:"بقدّر الناس الحقيقية.",note:"احترام"},
{id:567,en:"Respect is very important.",ar:"الاحترام مهم جدًا.",note:"علاقات"},
{id:568,en:"Kindness makes a difference.",ar:"الطيبة بتفرق.",note:"حكمة"},
{id:569,en:"A small gesture means a lot.",ar:"التصرف البسيط بيفرق جدًا.",note:"امتنان"},
{id:570,en:"Words can heal people.",ar:"الكلام ممكن يداوي الناس.",note:"مشاعر"},

{id:571,en:"I’m trying to think positively.",ar:"بحاول أفكر بإيجابية.",note:"إيجابية"},
{id:572,en:"Negative thoughts are exhausting.",ar:"الأفكار السلبية مرهقة.",note:"تفكير"},
{id:573,en:"I need to believe in myself.",ar:"لازم أؤمن بنفسي.",note:"ثقة"},
{id:574,en:"Fear stops many people.",ar:"الخوف بيوقف ناس كتير.",note:"خوف"},
{id:575,en:"Courage changes lives.",ar:"الشجاعة بتغير الحياة.",note:"شجاعة"},
{id:576,en:"I’m trying to overcome my fears.",ar:"بحاول أتغلب على خوفي.",note:"شجاعة"},
{id:577,en:"Growth begins outside your comfort zone.",ar:"التطور بيبدأ بره منطقة الراحة.",note:"تطوير"},
{id:578,en:"I need to challenge myself more.",ar:"لازم أتحدى نفسي أكتر.",note:"تطوير"},
{id:579,en:"I don’t want to stay stuck.",ar:"مش عايز أفضل واقف مكاني.",note:"طموح"},
{id:580,en:"I’m ready for change.",ar:"أنا جاهز للتغيير.",note:"تغيير"},

{id:581,en:"I need to think about my future.",ar:"لازم أفكر في مستقبلي.",note:"مستقبل"},
{id:582,en:"I have big ambitions.",ar:"عندي طموحات كبيرة.",note:"طموح"},
{id:583,en:"I want to build something meaningful.",ar:"عايز أبني حاجة ليها قيمة.",note:"هدف"},
{id:584,en:"I’m working toward my dreams.",ar:"بشتغل على أحلامي.",note:"أحلام"},
{id:585,en:"Nothing happens without effort.",ar:"مفيش حاجة بتحصل من غير تعب.",note:"نجاح"},
{id:586,en:"I need to stay patient.",ar:"لازم أكون صبور.",note:"صبر"},
{id:587,en:"Good things need time.",ar:"الحاجات الحلوة محتاجة وقت.",note:"صبر"},
{id:588,en:"Every step matters.",ar:"كل خطوة ليها قيمة.",note:"تطوير"},
{id:589,en:"I’m getting closer to my goals.",ar:"بقرّب من أهدافي.",note:"أهداف"},
{id:590,en:"I won’t stop trying.",ar:"مش هبطل أحاول.",note:"إصرار"},

{id:591,en:"I’ve come a long way.",ar:"أنا وصلت لطريق طويل.",note:"إنجاز"},
{id:592,en:"I’m proud of my journey.",ar:"فخور برحلتي.",note:"فخر"},
{id:593,en:"I’ve grown a lot.",ar:"اتطورت جدًا.",note:"تطوير"},
{id:594,en:"I’m not the same anymore.",ar:"أنا مش زي زمان.",note:"تغيير"},
{id:595,en:"Life taught me many lessons.",ar:"الحياة علمتني دروس كتير.",note:"خبرة"},
{id:596,en:"I appreciate every experience now.",ar:"بقيت أقدّر كل تجربة.",note:"خبرة"},
{id:597,en:"Pain teaches valuable lessons.",ar:"الألم بيعلم دروس مهمة.",note:"حكمة"},
{id:598,en:"Everything shaped who I am today.",ar:"كل حاجة شكلت شخصيتي الحالية.",note:"حياة"},
{id:599,en:"I’m still learning every day.",ar:"لسه بتعلم كل يوم.",note:"تعلم"},
{id:600,en:"This is only the beginning.",ar:"دي مجرد البداية.",note:"بداية"},
{id:601,en:"I need to improve my lifestyle.",ar:"لازم أحسن أسلوب حياتي.",note:"حياة"},
{id:602,en:"Healthy habits make a difference.",ar:"العادات الصحية بتفرق.",note:"صحة"},
{id:603,en:"I should exercise more often.",ar:"لازم أتمرن أكتر.",note:"رياضة"},
{id:604,en:"I need to eat healthier food.",ar:"لازم آكل أكل صحي أكتر.",note:"صحة"},
{id:605,en:"Sleep is very important.",ar:"النوم مهم جدًا.",note:"صحة"},
{id:606,en:"I haven’t been taking care of myself.",ar:"ما كنتش باهتم بنفسي.",note:"صحة"},
{id:607,en:"I need better balance in my life.",ar:"محتاج توازن أفضل في حياتي.",note:"حياة"},
{id:608,en:"Work isn't everything.",ar:"الشغل مش كل حاجة.",note:"حياة"},
{id:609,en:"I need time for myself too.",ar:"لازم وقت لنفسي برضه.",note:"راحة"},
{id:610,en:"Resting is productive sometimes.",ar:"الراحة أحيانًا بتكون مفيدة.",note:"راحة"},

{id:611,en:"I need to stop wasting time.",ar:"لازم أبطل تضييع وقت.",note:"وقت"},
{id:612,en:"Time management is difficult.",ar:"تنظيم الوقت صعب.",note:"تنظيم"},
{id:613,en:"I procrastinate too much.",ar:"بأجل كتير.",note:"تنظيم"},
{id:614,en:"I need to be more disciplined.",ar:"لازم أكون ملتزم أكتر.",note:"تطوير"},
{id:615,en:"Small habits create big results.",ar:"العادات الصغيرة بتعمل نتائج كبيرة.",note:"تطوير"},
{id:616,en:"I’m building a better routine.",ar:"ببني روتين أفضل.",note:"تنظيم"},
{id:617,en:"Consistency beats motivation.",ar:"الاستمرارية أقوى من الحماس.",note:"نجاح"},
{id:618,en:"I need to stay committed.",ar:"لازم ألتزم.",note:"تطوير"},
{id:619,en:"I’m trying to stay productive.",ar:"بحاول أبقى منتج.",note:"إنتاجية"},
{id:620,en:"I need fewer distractions.",ar:"محتاج مشتتات أقل.",note:"تركيز"},

{id:621,en:"Social media wastes a lot of time.",ar:"السوشيال ميديا بتضيع وقت كتير.",note:"سوشيال"},
{id:622,en:"I spend too much time on my phone.",ar:"بقضي وقت كتير على موبايلي.",note:"هاتف"},
{id:623,en:"I need to disconnect for a while.",ar:"محتاج أفصل شوية.",note:"راحة"},
{id:624,en:"I want a quieter life.",ar:"عايز حياة أهدى.",note:"حياة"},
{id:625,en:"Peace of mind is priceless.",ar:"راحة البال مالهاش تمن.",note:"راحة"},
{id:626,en:"I don’t want unnecessary stress.",ar:"مش عايز ضغط زيادة.",note:"ضغط"},
{id:627,en:"I’m trying to simplify my life.",ar:"بحاول أبسط حياتي.",note:"حياة"},
{id:628,en:"Less drama means more peace.",ar:"دراما أقل يعني راحة أكتر.",note:"راحة"},
{id:629,en:"I need positive energy around me.",ar:"محتاج طاقة إيجابية حواليا.",note:"طاقة"},
{id:630,en:"I avoid toxic people now.",ar:"ببعد عن الناس السامة دلوقتي.",note:"علاقات"},

{id:631,en:"I learned to say no.",ar:"اتعلمت أقول لأ.",note:"حدود"},
{id:632,en:"You can’t please everyone.",ar:"مش هتقدر ترضي كل الناس.",note:"حكمة"},
{id:633,en:"Setting boundaries is important.",ar:"وضع الحدود مهم.",note:"علاقات"},
{id:634,en:"I respect myself more now.",ar:"بقيت أحترم نفسي أكتر.",note:"ثقة"},
{id:635,en:"Confidence changes your attitude.",ar:"الثقة بتغير أسلوبك.",note:"ثقة"},
{id:636,en:"I know what I deserve.",ar:"أنا عارف أستحق إيه.",note:"ثقة"},
{id:637,en:"I stopped chasing approval.",ar:"بطلت أدور على موافقة الناس.",note:"تطوير"},
{id:638,en:"I trust myself more than before.",ar:"بثق في نفسي أكتر من زمان.",note:"ثقة"},
{id:639,en:"I learned from every failure.",ar:"اتعلمت من كل فشل.",note:"تعلم"},
{id:640,en:"Mistakes help you improve.",ar:"الأخطاء بتساعدك تتحسن.",note:"تعلم"},

{id:641,en:"I’m not afraid of starting over.",ar:"مش خايف أبدأ من جديد.",note:"بداية"},
{id:642,en:"Every ending is a new beginning.",ar:"كل نهاية هي بداية جديدة.",note:"حياة"},
{id:643,en:"I’m trying to move forward.",ar:"بحاول أتحرك لقدام.",note:"تطوير"},
{id:644,en:"I don’t live in the past anymore.",ar:"ما بقيتش عايش في الماضي.",note:"تطوير"},
{id:645,en:"I’m focused on the future.",ar:"أنا مركز على المستقبل.",note:"مستقبل"},
{id:646,en:"My goals are clear now.",ar:"أهدافي بقت واضحة دلوقتي.",note:"أهداف"},
{id:647,en:"I need to stay determined.",ar:"لازم أفضل مصمم.",note:"إصرار"},
{id:648,en:"Nothing can stop me now.",ar:"مفيش حاجة هتوقفني دلوقتي.",note:"ثقة"},
{id:649,en:"I believe in my potential.",ar:"مؤمن بإمكانياتي.",note:"ثقة"},
{id:650,en:"I’m stronger than my fears.",ar:"أنا أقوى من خوفي.",note:"شجاعة"},

{id:651,en:"Fear holds many people back.",ar:"الخوف بيعطل ناس كتير.",note:"خوف"},
{id:652,en:"Courage opens new doors.",ar:"الشجاعة بتفتح أبواب جديدة.",note:"شجاعة"},
{id:653,en:"I need to take more risks.",ar:"لازم أخاطر أكتر.",note:"تطوير"},
{id:654,en:"Growth requires discomfort.",ar:"التطور يحتاج خروج من الراحة.",note:"تطوير"},
{id:655,en:"I’m ready to challenge myself.",ar:"أنا جاهز أتحدى نفسي.",note:"تطوير"},
{id:656,en:"Comfort zones limit growth.",ar:"منطقة الراحة بتحد التطور.",note:"تطوير"},
{id:657,en:"I want to reach my full potential.",ar:"عايز أوصل لأقصى إمكانياتي.",note:"طموح"},
{id:658,en:"I need to believe in the process.",ar:"لازم أثق في الرحلة.",note:"تطوير"},
{id:659,en:"Success takes consistency and patience.",ar:"النجاح يحتاج استمرارية وصبر.",note:"نجاح"},
{id:660,en:"I won’t quit halfway.",ar:"مش هوقف في النص.",note:"إصرار"},

{id:661,en:"I’m learning to enjoy the journey.",ar:"بتعلم أستمتع بالرحلة.",note:"حياة"},
{id:662,en:"Life isn’t a race.",ar:"الحياة مش سباق.",note:"حكمة"},
{id:663,en:"Everyone moves at their own pace.",ar:"كل واحد بيمشي بسرعته.",note:"حكمة"},
{id:664,en:"Comparison steals happiness.",ar:"المقارنة بتسرق السعادة.",note:"حكمة"},
{id:665,en:"I focus on my own progress.",ar:"بركز على تقدمي أنا.",note:"تطوير"},
{id:666,en:"I’m grateful for what I have.",ar:"ممتن للي عندي.",note:"امتنان"},
{id:667,en:"Gratitude changes your mindset.",ar:"الامتنان بيغير طريقة التفكير.",note:"إيجابية"},
{id:668,en:"Simple things bring happiness.",ar:"الحاجات البسيطة بتجيب السعادة.",note:"حياة"},
{id:669,en:"I enjoy peaceful moments.",ar:"بحب اللحظات الهادية.",note:"راحة"},
{id:670,en:"I appreciate the little things.",ar:"بقدّر الحاجات الصغيرة.",note:"امتنان"},

{id:671,en:"I need to reconnect with myself.",ar:"محتاج أرجع أتواصل مع نفسي.",note:"تطوير"},
{id:672,en:"Sometimes silence is necessary.",ar:"أحيانًا السكوت ضروري.",note:"حكمة"},
{id:673,en:"I think too much at night.",ar:"بفكر كتير بالليل.",note:"تفكير"},
{id:674,en:"Nighttime makes me reflective.",ar:"الليل بيخليني أفكر.",note:"تفكير"},
{id:675,en:"I need inner peace.",ar:"محتاج سلام داخلي.",note:"راحة"},
{id:676,en:"I’m learning emotional control.",ar:"بتعلم أتحكم في مشاعري.",note:"مشاعر"},
{id:677,en:"Not every reaction is necessary.",ar:"مش كل رد فعل ضروري.",note:"حكمة"},
{id:678,en:"I choose calm over chaos.",ar:"بختار الهدوء بدل الفوضى.",note:"راحة"},
{id:679,en:"I don’t want unnecessary conflict.",ar:"مش عايز صراعات زيادة.",note:"هدوء"},
{id:680,en:"I value emotional stability.",ar:"بقدّر الاستقرار النفسي.",note:"مشاعر"},

{id:681,en:"I’m learning to forgive myself.",ar:"بتعلم أسامح نفسي.",note:"تطوير"},
{id:682,en:"Nobody is perfect.",ar:"مفيش حد كامل.",note:"حكمة"},
{id:683,en:"We all make mistakes.",ar:"كلنا بنغلط.",note:"حكمة"},
{id:684,en:"Failure is part of growth.",ar:"الفشل جزء من التطور.",note:"تطوير"},
{id:685,en:"I’m proud of how far I’ve come.",ar:"فخور بالمشوار اللي وصلتله.",note:"فخر"},
{id:686,en:"I survived difficult moments.",ar:"عدّيت لحظات صعبة.",note:"قوة"},
{id:687,en:"Hard times made me stronger.",ar:"الأوقات الصعبة قوتني.",note:"قوة"},
{id:688,en:"Pain changes people.",ar:"الألم بيغير الناس.",note:"حياة"},
{id:689,en:"Experience teaches powerful lessons.",ar:"الخبرة بتعلم دروس قوية.",note:"خبرة"},
{id:690,en:"Life keeps teaching me.",ar:"الحياة لسه بتعلمني.",note:"تعلم"},

{id:691,en:"I still have a lot to achieve.",ar:"لسه عندي حاجات كتير أحققها.",note:"طموح"},
{id:692,en:"I’m hungry for success.",ar:"عندي شغف للنجاح.",note:"نجاح"},
{id:693,en:"I want financial freedom.",ar:"عايز حرية مالية.",note:"مال"},
{id:694,en:"I want a meaningful life.",ar:"عايز حياة لها معنى.",note:"حياة"},
{id:695,en:"I’m building my future step by step.",ar:"ببني مستقبلي خطوة خطوة.",note:"مستقبل"},
{id:696,en:"Every effort counts.",ar:"كل مجهود له قيمة.",note:"تحفيز"},
{id:697,en:"I’m not giving up on my dreams.",ar:"مش هتنازل عن أحلامي.",note:"أحلام"},
{id:698,en:"I believe better days are ahead.",ar:"مؤمن إن الأيام الأحسن جاية.",note:"تفاؤل"},
{id:699,en:"I’m ready for the next chapter.",ar:"أنا جاهز للمرحلة الجاية.",note:"بداية"},
{id:700,en:"My journey is just beginning.",ar:"رحلتي لسه بتبدأ.",note:"بداية"},
{id:701,en:"I need to organize my thoughts.",ar:"محتاج أرتب أفكاري.",note:"تفكير"},
{id:702,en:"Too many things are happening at once.",ar:"حاجات كتير بتحصل مرة واحدة.",note:"ضغط"},
{id:703,en:"I need a moment to think.",ar:"محتاج لحظة أفكر.",note:"تفكير"},
{id:704,en:"I feel overwhelmed sometimes.",ar:"أحيانًا بحس إن كل حاجة فوق طاقتي.",note:"ضغط"},
{id:705,en:"I’m trying to stay balanced.",ar:"بحاول أحافظ على توازني.",note:"توازن"},
{id:706,en:"Balance is important in life.",ar:"التوازن مهم في الحياة.",note:"حكمة"},
{id:707,en:"I need to prioritize better.",ar:"لازم أرتب أولوياتي أحسن.",note:"تنظيم"},
{id:708,en:"I waste too much energy worrying.",ar:"بضيع طاقة كتير في القلق.",note:"قلق"},
{id:709,en:"I need to focus on solutions.",ar:"لازم أركز على الحلول.",note:"حل مشاكل"},
{id:710,en:"Stress affects everything.",ar:"الضغط بيأثر على كل حاجة.",note:"ضغط"},

{id:711,en:"I’m learning how to stay calm.",ar:"بتعلم إزاي أكون هادي.",note:"هدوء"},
{id:712,en:"Breathing deeply helps me relax.",ar:"التنفس العميق بيريحني.",note:"راحة"},
{id:713,en:"I need more quiet in my life.",ar:"محتاج هدوء أكتر في حياتي.",note:"راحة"},
{id:714,en:"Peace is my priority now.",ar:"راحة البال أولويتي دلوقتي.",note:"راحة"},
{id:715,en:"I avoid unnecessary arguments.",ar:"بتجنب الجدال اللي ملوش لازمة.",note:"هدوء"},
{id:716,en:"I don't want negative energy.",ar:"مش عايز طاقة سلبية.",note:"طاقة"},
{id:717,en:"I protect my mental health.",ar:"بحافظ على صحتي النفسية.",note:"صحة"},
{id:718,en:"I need healthier relationships.",ar:"محتاج علاقات صحية أكتر.",note:"علاقات"},
{id:719,en:"Some people drain your energy.",ar:"في ناس بتسحب طاقتك.",note:"علاقات"},
{id:720,en:"I choose peace over conflict.",ar:"بختار السلام بدل الصراع.",note:"راحة"},

{id:721,en:"I’m becoming more self-aware.",ar:"بقيت واعي بنفسي أكتر.",note:"تطوير"},
{id:722,en:"I understand myself better now.",ar:"بقيت فاهم نفسي أكتر دلوقتي.",note:"تطوير"},
{id:723,en:"Growth starts with self-awareness.",ar:"التطور يبدأ بفهم نفسك.",note:"تطوير"},
{id:724,en:"I’m trying to control my emotions.",ar:"بحاول أتحكم في مشاعري.",note:"مشاعر"},
{id:725,en:"Emotional control is a skill.",ar:"التحكم في المشاعر مهارة.",note:"تطوير"},
{id:726,en:"I need to react less emotionally.",ar:"لازم أبطل ردود الفعل العاطفية.",note:"مشاعر"},
{id:727,en:"Not everything deserves a reaction.",ar:"مش كل حاجة تستحق رد فعل.",note:"حكمة"},
{id:728,en:"Silence can solve many problems.",ar:"السكوت ممكن يحل مشاكل كتير.",note:"حكمة"},
{id:729,en:"I’m learning patience every day.",ar:"بتعلم الصبر كل يوم.",note:"صبر"},
{id:730,en:"Patience changes your perspective.",ar:"الصبر بيغير نظرتك.",note:"حكمة"},

{id:731,en:"I need to stop doubting myself.",ar:"لازم أبطل أشك في نفسي.",note:"ثقة"},
{id:732,en:"Confidence takes time to build.",ar:"الثقة بتاخد وقت علشان تتبني.",note:"ثقة"},
{id:733,en:"I believe in my abilities.",ar:"مؤمن بقدراتي.",note:"ثقة"},
{id:734,en:"I’m more capable than I think.",ar:"أنا أقدر على أكتر مما أتخيل.",note:"ثقة"},
{id:735,en:"Fear limits potential.",ar:"الخوف بيحد الإمكانيات.",note:"خوف"},
{id:736,en:"I need to step out of my comfort zone.",ar:"لازم أخرج من منطقة الراحة.",note:"تطوير"},
{id:737,en:"Taking risks can change your life.",ar:"المخاطرة ممكن تغير حياتك.",note:"تطوير"},
{id:738,en:"I’m ready for bigger challenges.",ar:"أنا جاهز لتحديات أكبر.",note:"تطوير"},
{id:739,en:"Challenges help us grow.",ar:"التحديات بتساعدنا نتطور.",note:"تطوير"},
{id:740,en:"I’m stronger than my excuses.",ar:"أنا أقوى من أعذاري.",note:"تحفيز"},

{id:741,en:"I need to stop comparing myself to others.",ar:"لازم أبطل أقارن نفسي بغيري.",note:"تطوير"},
{id:742,en:"Everyone has their own path.",ar:"كل واحد له طريقه.",note:"حكمة"},
{id:743,en:"Comparison steals joy.",ar:"المقارنة بتسرق الفرحة.",note:"حكمة"},
{id:744,en:"I focus on my own progress.",ar:"بركز على تقدمي أنا.",note:"تطوير"},
{id:745,en:"I’m proud of my growth.",ar:"فخور بتطوري.",note:"فخر"},
{id:746,en:"I appreciate how far I’ve come.",ar:"بقدّر المشوار اللي وصلتله.",note:"امتنان"},
{id:747,en:"Success looks different for everyone.",ar:"النجاح شكله مختلف لكل شخص.",note:"نجاح"},
{id:748,en:"I define success my own way.",ar:"أنا اللي بحدد معنى النجاح بالنسبالي.",note:"نجاح"},
{id:749,en:"Money isn’t the only measure of success.",ar:"الفلوس مش المقياس الوحيد للنجاح.",note:"نجاح"},
{id:750,en:"Inner peace is real success.",ar:"راحة البال هي النجاح الحقيقي.",note:"راحة"},

{id:751,en:"I need to improve my habits.",ar:"لازم أحسن عاداتي.",note:"تطوير"},
{id:752,en:"Good habits create better lives.",ar:"العادات الجيدة بتعمل حياة أفضل.",note:"تطوير"},
{id:753,en:"Small actions matter.",ar:"الأفعال الصغيرة بتفرق.",note:"تطوير"},
{id:754,en:"I’m building discipline slowly.",ar:"ببني الالتزام واحدة واحدة.",note:"تطوير"},
{id:755,en:"Discipline creates freedom.",ar:"الالتزام بيخلق حرية.",note:"حكمة"},
{id:756,en:"Consistency is more important than perfection.",ar:"الاستمرارية أهم من الكمال.",note:"نجاح"},
{id:757,en:"I need to trust gradual progress.",ar:"لازم أثق في التقدم التدريجي.",note:"تطوير"},
{id:758,en:"Every day is a new chance to improve.",ar:"كل يوم فرصة جديدة للتحسن.",note:"تحفيز"},
{id:759,en:"I’m becoming more focused.",ar:"بقيت مركز أكتر.",note:"تركيز"},
{id:760,en:"Focus creates results.",ar:"التركيز بيعمل نتائج.",note:"نجاح"},

{id:761,en:"I need fewer distractions in my life.",ar:"محتاج مشتتات أقل في حياتي.",note:"تركيز"},
{id:762,en:"Social media affects my focus.",ar:"السوشيال ميديا بتأثر على تركيزي.",note:"سوشيال"},
{id:763,en:"I need more real-life experiences.",ar:"محتاج تجارب حقيقية أكتر.",note:"حياة"},
{id:764,en:"Real connections matter more.",ar:"العلاقات الحقيقية أهم.",note:"علاقات"},
{id:765,en:"I value meaningful conversations.",ar:"بقدّر الكلام اللي له معنى.",note:"محادثات"},
{id:766,en:"I’m tired of superficial people.",ar:"زهقت من الناس السطحية.",note:"علاقات"},
{id:767,en:"Authenticity matters to me.",ar:"الحقيقة مهمة بالنسبالي.",note:"صراحة"},
{id:768,en:"I appreciate honest people.",ar:"بقدّر الناس الصريحة.",note:"احترام"},
{id:769,en:"Trust is earned over time.",ar:"الثقة بتتكتسب مع الوقت.",note:"ثقة"},
{id:770,en:"Loyalty is rare these days.",ar:"الوفاء بقى نادر الأيام دي.",note:"علاقات"},

{id:771,en:"I’m learning to forgive.",ar:"بتعلم أسامح.",note:"تطوير"},
{id:772,en:"Holding grudges hurts you more.",ar:"الزعل بيأذيك إنت أكتر.",note:"حكمة"},
{id:773,en:"Forgiveness brings peace.",ar:"التسامح بيجيب راحة.",note:"راحة"},
{id:774,en:"I’m letting go of the past.",ar:"بسيب الماضي يمشي.",note:"تطوير"},
{id:775,en:"I don’t want emotional baggage.",ar:"مش عايز أحمل هموم قديمة.",note:"مشاعر"},
{id:776,en:"Healing takes time.",ar:"التعافي بياخد وقت.",note:"صبر"},
{id:777,en:"I’m still recovering emotionally.",ar:"لسه بتعافى نفسيًا.",note:"مشاعر"},
{id:778,en:"Some wounds take longer to heal.",ar:"في جروح بتاخد وقت أطول.",note:"مشاعر"},
{id:779,en:"I’m becoming emotionally stronger.",ar:"بقيت أقوى نفسيًا.",note:"قوة"},
{id:780,en:"Pain can teach valuable lessons.",ar:"الألم ممكن يعلم دروس مهمة.",note:"حكمة"},

{id:781,en:"I need to spend more time with family.",ar:"لازم أقضي وقت أكتر مع العيلة.",note:"عائلة"},
{id:782,en:"Family support means everything.",ar:"دعم العيلة يعني كل حاجة.",note:"عائلة"},
{id:783,en:"True friends stay during hard times.",ar:"الأصحاب الحقيقيين بيظهروا وقت الشدة.",note:"أصدقاء"},
{id:784,en:"I appreciate loyal people.",ar:"بقدّر الناس الوفية.",note:"علاقات"},
{id:785,en:"I need healthier friendships.",ar:"محتاج صداقات صحية أكتر.",note:"أصدقاء"},
{id:786,en:"Not everyone deserves access to you.",ar:"مش كل الناس تستحق تدخل حياتك.",note:"حدود"},
{id:787,en:"Protect your energy and time.",ar:"احمي وقتك وطاقتك.",note:"طاقة"},
{id:788,en:"Saying no is important sometimes.",ar:"قول لأ مهم أحيانًا.",note:"حدود"},
{id:789,en:"Boundaries create healthier relationships.",ar:"الحدود بتعمل علاقات صحية.",note:"علاقات"},
{id:790,en:"I respect myself more now.",ar:"بقيت أحترم نفسي أكتر.",note:"ثقة"},

{id:791,en:"I still have a lot to learn.",ar:"لسه عندي كتير أتعلمه.",note:"تعلم"},
{id:792,en:"Learning never stops.",ar:"التعلم عمره ما بيقف.",note:"تعلم"},
{id:793,en:"Experience is the best teacher.",ar:"الخبرة أفضل معلم.",note:"خبرة"},
{id:794,en:"Mistakes teach powerful lessons.",ar:"الأخطاء بتعلم دروس قوية.",note:"تعلم"},
{id:795,en:"I’m grateful for every lesson.",ar:"ممتن لكل درس اتعلمته.",note:"امتنان"},
{id:796,en:"Everything happens for growth.",ar:"كل حاجة بتحصل علشان التطور.",note:"تطوير"},
{id:797,en:"I trust the timing of my life.",ar:"بثق في توقيت حياتي.",note:"تفاؤل"},
{id:798,en:"Good things are coming.",ar:"الحاجات الحلوة جاية.",note:"تفاؤل"},
{id:799,en:"I’m excited for the future.",ar:"متحمس للمستقبل.",note:"مستقبل"},
{id:800,en:"My journey is still unfolding.",ar:"رحلتي لسه مستمرة.",note:"حياة"},
],

"daily":[],
"restaurants":[],
"work":[],
"travel":[],
"social":[],
"relationships":[],
"business":[],
"pronunciation":[]

};
